"""
30 Easy DSA coding problems with typed function signatures and 10 test cases each (2 visible, 8 hidden with edge cases).
"""

from backend.app.models.question import QuestionDifficulty

DSA_EASY_QUESTIONS = [
    {
        "title": "Two Sum Target",
        "description": "Given an array of integers `nums` and an integer `target`, return the indices of the two numbers such that they add up to `target`.\n\nYou may assume that each input would have exactly one solution, and you may not use the same element twice. Return the answer as an array of two integers in ascending order.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "twoSum",
        "parameters": [{"name": "nums", "type": "int[]"}, {"name": "target", "type": "int"}],
        "return_type": "int[]",
        "sample_input": "[2, 7, 11, 15]\n9",
        "sample_output": "[0, 1]",
        "input_format": "Line 1: nums (int array)\nLine 2: target (int)",
        "test_cases": [
            {"input": "[2, 7, 11, 15]\n9", "expected_output": "[0, 1]", "is_hidden": False, "weight": 1.0},
            {"input": "[3, 2, 4]\n6", "expected_output": "[1, 2]", "is_hidden": False, "weight": 1.0},
            {"input": "[3, 3]\n6", "expected_output": "[0, 1]", "is_hidden": True, "weight": 1.0},
            {"input": "[-1, -2, -3, -4, -5]\n-8", "expected_output": "[2, 4]", "is_hidden": True, "weight": 1.0},
            {"input": "[0, 4, 3, 0]\n0", "expected_output": "[0, 3]", "is_hidden": True, "weight": 1.0},
            {"input": "[-3, 4, 3, 90]\n0", "expected_output": "[0, 2]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 5, 8, 10, 14]\n19", "expected_output": "[1, 4]", "is_hidden": True, "weight": 1.0},
            {"input": "[100, 200, 300, 400]\n700", "expected_output": "[2, 3]", "is_hidden": True, "weight": 1.0},
            {"input": "[5, 75, 25]\n100", "expected_output": "[1, 2]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]\n19", "expected_output": "[8, 9]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Valid Palindrome",
        "description": "A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward.\n\nGiven a string `s`, return `true` if it is a palindrome, or `false` otherwise.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "isPalindrome",
        "parameters": [{"name": "s", "type": "string"}],
        "return_type": "bool",
        "sample_input": "\"A man, a plan, a canal: Panama\"",
        "sample_output": "true",
        "input_format": "Line 1: string s",
        "test_cases": [
            {"input": "\"A man, a plan, a canal: Panama\"", "expected_output": "true", "is_hidden": False, "weight": 1.0},
            {"input": "\"race a car\"", "expected_output": "false", "is_hidden": False, "weight": 1.0},
            {"input": "\" \"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"0P\"", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "\"ab_a\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\".,\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"Was it a car or a cat I saw?\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"1b1\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"No 'x' in Nixon\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"abcba1\"", "expected_output": "false", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Valid Parentheses",
        "description": "Given a string `s` containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.\n\nAn input string is valid if open brackets are closed by the same type of brackets and closed in the correct order.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "isValid",
        "parameters": [{"name": "s", "type": "string"}],
        "return_type": "bool",
        "sample_input": "\"()[]{}\"",
        "sample_output": "true",
        "input_format": "Line 1: string s",
        "test_cases": [
            {"input": "\"()[]{}\"", "expected_output": "true", "is_hidden": False, "weight": 1.0},
            {"input": "\"(]\"", "expected_output": "false", "is_hidden": False, "weight": 1.0},
            {"input": "\"([)]\"", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "\"{[]}\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"(\"", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "\"]\"", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "\"((((()))))\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"{[()()]}\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"((()))(())\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Fibonacci Number",
        "description": "The Fibonacci numbers form a sequence where F(0) = 0, F(1) = 1, and F(n) = F(n - 1) + F(n - 2) for n > 1.\n\nGiven n, calculate F(n).",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "fib",
        "parameters": [{"name": "n", "type": "int"}],
        "return_type": "int",
        "sample_input": "4",
        "sample_output": "3",
        "input_format": "Line 1: integer n",
        "test_cases": [
            {"input": "2", "expected_output": "1", "is_hidden": False, "weight": 1.0},
            {"input": "4", "expected_output": "3", "is_hidden": False, "weight": 1.0},
            {"input": "0", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "1", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "3", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "5", "expected_output": "5", "is_hidden": True, "weight": 1.0},
            {"input": "6", "expected_output": "8", "is_hidden": True, "weight": 1.0},
            {"input": "8", "expected_output": "21", "is_hidden": True, "weight": 1.0},
            {"input": "10", "expected_output": "55", "is_hidden": True, "weight": 1.0},
            {"input": "15", "expected_output": "610", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Contains Duplicate",
        "description": "Given an integer array `nums`, return `true` if any value appears at least twice in the array, and return `false` if every element is distinct.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "containsDuplicate",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "bool",
        "sample_input": "[1, 2, 3, 1]",
        "sample_output": "true",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[1, 2, 3, 1]", "expected_output": "true", "is_hidden": False, "weight": 1.0},
            {"input": "[1, 2, 3, 4]", "expected_output": "false", "is_hidden": False, "weight": 1.0},
            {"input": "[1, 1, 1, 3, 3, 4, 3, 2, 4, 2]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "[]", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "[42]", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "[-1, -1]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "[-1, 1]", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "[0, 0]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "[10, 20, 30, 40, 50, 60, 70, 80, 90, 10]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Best Time to Buy and Sell Stock",
        "description": "You are given an array `prices` where `prices[i]` is the price of a given stock on the $i^{th}$ day.\n\nYou want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock. Return the maximum profit you can achieve. If you cannot achieve any profit, return 0.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "maxProfit",
        "parameters": [{"name": "prices", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "[7, 1, 5, 3, 6, 4]",
        "sample_output": "5",
        "input_format": "Line 1: prices (int array)",
        "test_cases": [
            {"input": "[7, 1, 5, 3, 6, 4]", "expected_output": "5", "is_hidden": False, "weight": 1.0},
            {"input": "[7, 6, 4, 3, 1]", "expected_output": "0", "is_hidden": False, "weight": 1.0},
            {"input": "[1, 2]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 4, 1]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[3, 2, 6, 5, 0, 3]", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 1, 2, 1, 0, 1, 2]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[5]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3, 4, 5]", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[100, 180, 260, 310, 40, 535, 695]", "expected_output": "655", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Valid Anagram",
        "description": "Given two strings `s` and `t`, return `true` if `t` is an anagram of `s`, and `false` otherwise.\n\nAn Anagram is a word formed by rearranging the letters of a different word, typically using all the original letters exactly once.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "isAnagram",
        "parameters": [{"name": "s", "type": "string"}, {"name": "t", "type": "string"}],
        "return_type": "bool",
        "sample_input": "\"anagram\"\n\"nagaram\"",
        "sample_output": "true",
        "input_format": "Line 1: string s\nLine 2: string t",
        "test_cases": [
            {"input": "\"anagram\"\n\"nagaram\"", "expected_output": "true", "is_hidden": False, "weight": 1.0},
            {"input": "\"rat\"\n\"car\"", "expected_output": "false", "is_hidden": False, "weight": 1.0},
            {"input": "\"a\"\n\"a\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"a\"\n\"b\"", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "\"ab\"\n\"a\"", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "\"listen\"\n\"silent\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"triangle\"\n\"integral\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"apple\"\n\"pale\"", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "\"\"\n\"\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"dormitory\"\n\"dirtyroom\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Binary Search",
        "description": "Given an array of integers `nums` which is sorted in ascending order, and an integer `target`, write a function to search `target` in `nums`. If `target` exists, then return its index. Otherwise, return -1.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "search",
        "parameters": [{"name": "nums", "type": "int[]"}, {"name": "target", "type": "int"}],
        "return_type": "int",
        "sample_input": "[-1, 0, 3, 5, 9, 12]\n9",
        "sample_output": "4",
        "input_format": "Line 1: nums (int array)\nLine 2: target (int)",
        "test_cases": [
            {"input": "[-1, 0, 3, 5, 9, 12]\n9", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "[-1, 0, 3, 5, 9, 12]\n2", "expected_output": "-1", "is_hidden": False, "weight": 1.0},
            {"input": "[5]\n5", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[5]\n-5", "expected_output": "-1", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 3]\n3", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 3]\n1", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 3, 5, 7, 9, 11]\n1", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 3, 5, 7, 9, 11]\n11", "expected_output": "5", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 3, 5, 7, 9, 11]\n6", "expected_output": "-1", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]\n14", "expected_output": "6", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Maximum Subarray Sum",
        "description": "Given an integer array `nums`, find the subarray with the largest sum, and return its sum.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "maxSubArray",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "[-2, 1, -3, 4, -1, 2, 1, -5, 4]",
        "sample_output": "6",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[-2, 1, -3, 4, -1, 2, 1, -5, 4]", "expected_output": "6", "is_hidden": False, "weight": 1.0},
            {"input": "[1]", "expected_output": "1", "is_hidden": False, "weight": 1.0},
            {"input": "[5, 4, -1, 7, 8]", "expected_output": "23", "is_hidden": True, "weight": 1.0},
            {"input": "[-1]", "expected_output": "-1", "is_hidden": True, "weight": 1.0},
            {"input": "[-2, -1]", "expected_output": "-1", "is_hidden": True, "weight": 1.0},
            {"input": "[-3, -2, -2, -3]", "expected_output": "-2", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3, 4, 5]", "expected_output": "15", "is_hidden": True, "weight": 1.0},
            {"input": "[1, -2, 3, 10, -4, 7, 2, -5]", "expected_output": "18", "is_hidden": True, "weight": 1.0},
            {"input": "[0, 0, 0, 0]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[-2, 1, -3, 4, -1, 2, 1, -5, 4, 10]", "expected_output": "16", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Reverse String",
        "description": "Write a function that reverses a string and returns the reversed string.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "reverseString",
        "parameters": [{"name": "s", "type": "string"}],
        "return_type": "string",
        "sample_input": "\"hello\"",
        "sample_output": "\"olleh\"",
        "input_format": "Line 1: string s",
        "test_cases": [
            {"input": "\"hello\"", "expected_output": "\"olleh\"", "is_hidden": False, "weight": 1.0},
            {"input": "\"Hannah\"", "expected_output": "\"hannaH\"", "is_hidden": False, "weight": 1.0},
            {"input": "\"a\"", "expected_output": "\"a\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"\"", "expected_output": "\"\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"racecar\"", "expected_output": "\"racecar\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"12345\"", "expected_output": "\"54321\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"ab\"", "expected_output": "\"ba\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"algorithm\"", "expected_output": "\"mhtirogla\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"Antigravity\"", "expected_output": "\"ytivargitnA\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"A B C\"", "expected_output": "\"C B A\"", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Single Number",
        "description": "Given a non-empty array of integers `nums`, every element appears twice except for one. Find that single one.\n\nYou must implement a solution with a linear runtime complexity and use only constant extra space.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "singleNumber",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "[2, 2, 1]",
        "sample_output": "1",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[2, 2, 1]", "expected_output": "1", "is_hidden": False, "weight": 1.0},
            {"input": "[4, 1, 2, 1, 2]", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "[1]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[-1, -1, -2]", "expected_output": "-2", "is_hidden": True, "weight": 1.0},
            {"input": "[0, 1, 0]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[9, 3, 9, 3, 9, 7, 9]", "expected_output": "7", "is_hidden": True, "weight": 1.0},
            {"input": "[100, 200, 300, 200, 100]", "expected_output": "300", "is_hidden": True, "weight": 1.0},
            {"input": "[-5, 3, -5]", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "[123456]", "expected_output": "123456", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 3, 4, 5, 6, 5, 4, 3, 2]", "expected_output": "6", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Majority Element",
        "description": "Given an array `nums` of size `n`, return the majority element.\n\nThe majority element is the element that appears more than ⌊n / 2⌋ times. You may assume that the majority element always exists in the array.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "majorityElement",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "[3, 2, 3]",
        "sample_output": "3",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[3, 2, 3]", "expected_output": "3", "is_hidden": False, "weight": 1.0},
            {"input": "[2, 2, 1, 1, 1, 2, 2]", "expected_output": "2", "is_hidden": False, "weight": 1.0},
            {"input": "[1]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[6, 5, 5]", "expected_output": "5", "is_hidden": True, "weight": 1.0},
            {"input": "[-1, 1, 1, 1, 2, 1]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[10, 10, 20, 10, 30, 10, 10]", "expected_output": "10", "is_hidden": True, "weight": 1.0},
            {"input": "[7, 7, 7, 8, 8]", "expected_output": "7", "is_hidden": True, "weight": 1.0},
            {"input": "[9, 9, 9, 9, 9]", "expected_output": "9", "is_hidden": True, "weight": 1.0},
            {"input": "[-5, -5, -5, 2, 3]", "expected_output": "-5", "is_hidden": True, "weight": 1.0},
            {"input": "[100, 2, 100, 3, 100, 4, 100]", "expected_output": "100", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Move Zeroes",
        "description": "Given an integer array `nums`, move all 0's to the end of it while maintaining the relative order of the non-zero elements.\n\nReturn the modified array.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "moveZeroes",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int[]",
        "sample_input": "[0, 1, 0, 3, 12]",
        "sample_output": "[1, 3, 12, 0, 0]",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[0, 1, 0, 3, 12]", "expected_output": "[1, 3, 12, 0, 0]", "is_hidden": False, "weight": 1.0},
            {"input": "[0]", "expected_output": "[0]", "is_hidden": False, "weight": 1.0},
            {"input": "[1, 2, 3]", "expected_output": "[1, 2, 3]", "is_hidden": True, "weight": 1.0},
            {"input": "[0, 0, 0]", "expected_output": "[0, 0, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 0]", "expected_output": "[1, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[0, 1]", "expected_output": "[1, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[4, 2, 4, 0, 0, 3, 0, 5, 1, 0]", "expected_output": "[4, 2, 4, 3, 5, 1, 0, 0, 0, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[-1, 0, -2, 0, -3]", "expected_output": "[-1, -2, -3, 0, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[0, 0, 1]", "expected_output": "[1, 0, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 1]", "expected_output": "[2, 1]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Missing Number",
        "description": "Given an array `nums` containing `n` distinct numbers in the range `[0, n]`, return the only number in the range that is missing from the array.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "missingNumber",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "[3, 0, 1]",
        "sample_output": "2",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[3, 0, 1]", "expected_output": "2", "is_hidden": False, "weight": 1.0},
            {"input": "[0, 1]", "expected_output": "2", "is_hidden": False, "weight": 1.0},
            {"input": "[9, 6, 4, 2, 3, 5, 7, 0, 1]", "expected_output": "8", "is_hidden": True, "weight": 1.0},
            {"input": "[0]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[1]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[0, 2, 3]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[5, 4, 3, 2, 1]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[0, 1, 2, 3, 4, 5, 6, 8]", "expected_output": "7", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 0, 3, 4, 5]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Roman to Integer",
        "description": "Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M.\n\nSymbol values: I = 1, V = 5, X = 10, L = 50, C = 100, D = 500, M = 1000.\n\nGiven a roman numeral `s`, convert it to an integer.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "romanToInt",
        "parameters": [{"name": "s", "type": "string"}],
        "return_type": "int",
        "sample_input": "\"III\"",
        "sample_output": "3",
        "input_format": "Line 1: string s",
        "test_cases": [
            {"input": "\"III\"", "expected_output": "3", "is_hidden": False, "weight": 1.0},
            {"input": "\"LVIII\"", "expected_output": "58", "is_hidden": False, "weight": 1.0},
            {"input": "\"MCMXCIV\"", "expected_output": "1994", "is_hidden": True, "weight": 1.0},
            {"input": "\"IV\"", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "\"IX\"", "expected_output": "9", "is_hidden": True, "weight": 1.0},
            {"input": "\"XL\"", "expected_output": "40", "is_hidden": True, "weight": 1.0},
            {"input": "\"XC\"", "expected_output": "90", "is_hidden": True, "weight": 1.0},
            {"input": "\"CD\"", "expected_output": "400", "is_hidden": True, "weight": 1.0},
            {"input": "\"CM\"", "expected_output": "900", "is_hidden": True, "weight": 1.0},
            {"input": "\"MMMCMXCIX\"", "expected_output": "3999", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Longest Common Prefix",
        "description": "Write a function to find the longest common prefix string amongst an array of strings. If there is no common prefix, return an empty string `\"\"`.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "longestCommonPrefix",
        "parameters": [{"name": "strs", "type": "string[]"}],
        "return_type": "string",
        "sample_input": "[\"flower\", \"flow\", \"flight\"]",
        "sample_output": "\"fl\"",
        "input_format": "Line 1: strs (string array)",
        "test_cases": [
            {"input": "[\"flower\", \"flow\", \"flight\"]", "expected_output": "\"fl\"", "is_hidden": False, "weight": 1.0},
            {"input": "[\"dog\", \"racecar\", \"car\"]", "expected_output": "\"\"", "is_hidden": False, "weight": 1.0},
            {"input": "[\"a\"]", "expected_output": "\"a\"", "is_hidden": True, "weight": 1.0},
            {"input": "[\"\"]", "expected_output": "\"\"", "is_hidden": True, "weight": 1.0},
            {"input": "[\"interspecies\", \"interstellar\", \"interstate\"]", "expected_output": "\"inters\"", "is_hidden": True, "weight": 1.0},
            {"input": "[\"throne\", \"throne\"]", "expected_output": "\"throne\"", "is_hidden": True, "weight": 1.0},
            {"input": "[\"cir\", \"car\"]", "expected_output": "\"c\"", "is_hidden": True, "weight": 1.0},
            {"input": "[\"reflower\", \"flow\", \"flight\"]", "expected_output": "\"\"", "is_hidden": True, "weight": 1.0},
            {"input": "[\"prefix\", \"preheat\", \"preview\"]", "expected_output": "\"pre\"", "is_hidden": True, "weight": 1.0},
            {"input": "[\"aa\", \"a\"]", "expected_output": "\"a\"", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Search Insert Position",
        "description": "Given a sorted array of distinct integers and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.\n\nYou must write an algorithm with $O(\\log n)$ runtime complexity.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "searchInsert",
        "parameters": [{"name": "nums", "type": "int[]"}, {"name": "target", "type": "int"}],
        "return_type": "int",
        "sample_input": "[1, 3, 5, 6]\n5",
        "sample_output": "2",
        "input_format": "Line 1: nums (int array)\nLine 2: target (int)",
        "test_cases": [
            {"input": "[1, 3, 5, 6]\n5", "expected_output": "2", "is_hidden": False, "weight": 1.0},
            {"input": "[1, 3, 5, 6]\n2", "expected_output": "1", "is_hidden": False, "weight": 1.0},
            {"input": "[1, 3, 5, 6]\n7", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 3, 5, 6]\n0", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[1]\n0", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[1]\n2", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[1]\n1", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 4, 6, 8, 10]\n5", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 4, 6, 8, 10]\n9", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 4, 6, 8, 10]\n11", "expected_output": "5", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Length of Last Word",
        "description": "Given a string `s` consisting of words and spaces, return the length of the last word in the string. A word is a maximal substring consisting of non-space characters only.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "lengthOfLastWord",
        "parameters": [{"name": "s", "type": "string"}],
        "return_type": "int",
        "sample_input": "\"Hello World\"",
        "sample_output": "5",
        "input_format": "Line 1: string s",
        "test_cases": [
            {"input": "\"Hello World\"", "expected_output": "5", "is_hidden": False, "weight": 1.0},
            {"input": "\"   fly me   to   the moon  \"", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "\"luffy is still joyboy\"", "expected_output": "6", "is_hidden": True, "weight": 1.0},
            {"input": "\"a\"", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "\"a \"", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "\" day \"", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "\"today is a beautiful day\"", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "\"   singleword   \"", "expected_output": "10", "is_hidden": True, "weight": 1.0},
            {"input": "\"abc def ghi jkl\"", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "\"Python Java Cpp\"", "expected_output": "3", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Plus One",
        "description": "You are given a large integer represented as an integer array `digits`, where each `digits[i]` is the $i^{th}$ digit of the integer. The digits are ordered from most significant to least significant in left-to-right order. The large integer does not contain any leading 0's.\n\nIncrement the large integer by one and return the resulting array of digits.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "plusOne",
        "parameters": [{"name": "digits", "type": "int[]"}],
        "return_type": "int[]",
        "sample_input": "[1, 2, 3]",
        "sample_output": "[1, 2, 4]",
        "input_format": "Line 1: digits (int array)",
        "test_cases": [
            {"input": "[1, 2, 3]", "expected_output": "[1, 2, 4]", "is_hidden": False, "weight": 1.0},
            {"input": "[4, 3, 2, 1]", "expected_output": "[4, 3, 2, 2]", "is_hidden": False, "weight": 1.0},
            {"input": "[9]", "expected_output": "[1, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[9, 9, 9]", "expected_output": "[1, 0, 0, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[0]", "expected_output": "[1]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 9, 9]", "expected_output": "[2, 0, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[8, 9, 9, 9]", "expected_output": "[9, 0, 0, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 4, 9, 3, 9]", "expected_output": "[2, 4, 9, 4, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 0, 0, 0, 0]", "expected_output": "[1, 0, 0, 0, 1]", "is_hidden": True, "weight": 1.0},
            {"input": "[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]", "expected_output": "[9, 8, 7, 6, 5, 4, 3, 2, 1, 1]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Sqrt(x) Integer",
        "description": "Given a non-negative integer `x`, return the square root of `x` rounded down to the nearest integer. The returned integer should be non-negative as well.\n\nYou must not use any built-in exponent function or operator.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "mySqrt",
        "parameters": [{"name": "x", "type": "int"}],
        "return_type": "int",
        "sample_input": "4",
        "sample_output": "2",
        "input_format": "Line 1: integer x",
        "test_cases": [
            {"input": "4", "expected_output": "2", "is_hidden": False, "weight": 1.0},
            {"input": "8", "expected_output": "2", "is_hidden": False, "weight": 1.0},
            {"input": "0", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "1", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "2", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "9", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "16", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "25", "expected_output": "5", "is_hidden": True, "weight": 1.0},
            {"input": "100", "expected_output": "10", "is_hidden": True, "weight": 1.0},
            {"input": "2147395599", "expected_output": "46339", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Climbing Stairs",
        "description": "You are climbing a staircase. It takes `n` steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "climbStairs",
        "parameters": [{"name": "n", "type": "int"}],
        "return_type": "int",
        "sample_input": "2",
        "sample_output": "2",
        "input_format": "Line 1: integer n",
        "test_cases": [
            {"input": "2", "expected_output": "2", "is_hidden": False, "weight": 1.0},
            {"input": "3", "expected_output": "3", "is_hidden": False, "weight": 1.0},
            {"input": "1", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "4", "expected_output": "5", "is_hidden": True, "weight": 1.0},
            {"input": "5", "expected_output": "8", "is_hidden": True, "weight": 1.0},
            {"input": "6", "expected_output": "13", "is_hidden": True, "weight": 1.0},
            {"input": "7", "expected_output": "21", "is_hidden": True, "weight": 1.0},
            {"input": "8", "expected_output": "34", "is_hidden": True, "weight": 1.0},
            {"input": "10", "expected_output": "89", "is_hidden": True, "weight": 1.0},
            {"input": "20", "expected_output": "10946", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Remove Duplicates from Sorted Array",
        "description": "Given an integer array `nums` sorted in non-decreasing order, remove the duplicates such that each unique element appears only once while maintaining relative order. Return the array of unique elements.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "removeDuplicates",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int[]",
        "sample_input": "[1, 1, 2]",
        "sample_output": "[1, 2]",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[1, 1, 2]", "expected_output": "[1, 2]", "is_hidden": False, "weight": 1.0},
            {"input": "[0, 0, 1, 1, 1, 2, 2, 3, 3, 4]", "expected_output": "[0, 1, 2, 3, 4]", "is_hidden": False, "weight": 1.0},
            {"input": "[]", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
            {"input": "[1]", "expected_output": "[1]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 1, 1, 1]", "expected_output": "[1]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3]", "expected_output": "[1, 2, 3]", "is_hidden": True, "weight": 1.0},
            {"input": "[-3, -1, 0, 0, 0, 3, 3]", "expected_output": "[-3, -1, 0, 3]", "is_hidden": True, "weight": 1.0},
            {"input": "[-10, -10, -5, -5, 0, 5, 5, 10]", "expected_output": "[-10, -5, 0, 5, 10]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 1, 2, 2, 3, 3, 4, 4, 5, 5]", "expected_output": "[1, 2, 3, 4, 5]", "is_hidden": True, "weight": 1.0},
            {"input": "[100, 100, 100]", "expected_output": "[100]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Merge Sorted Array",
        "description": "You are given two integer arrays `nums1` and `nums2`, sorted in non-decreasing order. Return a new merged array sorted in non-decreasing order.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "mergeSorted",
        "parameters": [{"name": "nums1", "type": "int[]"}, {"name": "nums2", "type": "int[]"}],
        "return_type": "int[]",
        "sample_input": "[1, 2, 3]\n[2, 5, 6]",
        "sample_output": "[1, 2, 2, 3, 5, 6]",
        "input_format": "Line 1: nums1 (int array)\nLine 2: nums2 (int array)",
        "test_cases": [
            {"input": "[1, 2, 3]\n[2, 5, 6]", "expected_output": "[1, 2, 2, 3, 5, 6]", "is_hidden": False, "weight": 1.0},
            {"input": "[1]\n[]", "expected_output": "[1]", "is_hidden": False, "weight": 1.0},
            {"input": "[]\n[1]", "expected_output": "[1]", "is_hidden": True, "weight": 1.0},
            {"input": "[]\n[]", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 0]\n[1]", "expected_output": "[0, 1, 2]", "is_hidden": True, "weight": 1.0},
            {"input": "[-5, -1, 3]\n[-3, 0, 4]", "expected_output": "[-5, -3, -1, 0, 3, 4]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 3, 5]\n[2, 4, 6]", "expected_output": "[1, 2, 3, 4, 5, 6]", "is_hidden": True, "weight": 1.0},
            {"input": "[4, 5, 6]\n[1, 2, 3]", "expected_output": "[1, 2, 3, 4, 5, 6]", "is_hidden": True, "weight": 1.0},
            {"input": "[10, 20]\n[5, 15, 25]", "expected_output": "[5, 10, 15, 20, 25]", "is_hidden": True, "weight": 1.0},
            {"input": "[0]\n[0]", "expected_output": "[0, 0]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Intersection of Two Arrays",
        "description": "Given two integer arrays `nums1` and `nums2`, return an array of their intersection. Each element in the result must be unique and you may return the result in ascending sorted order.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "intersection",
        "parameters": [{"name": "nums1", "type": "int[]"}, {"name": "nums2", "type": "int[]"}],
        "return_type": "int[]",
        "sample_input": "[1, 2, 2, 1]\n[2, 2]",
        "sample_output": "[2]",
        "input_format": "Line 1: nums1 (int array)\nLine 2: nums2 (int array)",
        "test_cases": [
            {"input": "[1, 2, 2, 1]\n[2, 2]", "expected_output": "[2]", "is_hidden": False, "weight": 1.0},
            {"input": "[4, 9, 5]\n[9, 4, 9, 8, 4]", "expected_output": "[4, 9]", "is_hidden": False, "weight": 1.0},
            {"input": "[1, 2, 3]\n[4, 5, 6]", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
            {"input": "[]\n[1, 2]", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
            {"input": "[1]\n[1]", "expected_output": "[1]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3, 4, 5]\n[3, 4, 5, 6, 7]", "expected_output": "[3, 4, 5]", "is_hidden": True, "weight": 1.0},
            {"input": "[-1, -2, 3]\n[-2, 3, 4]", "expected_output": "[-2, 3]", "is_hidden": True, "weight": 1.0},
            {"input": "[0, 0, 0]\n[0, 0]", "expected_output": "[0]", "is_hidden": True, "weight": 1.0},
            {"input": "[10, 20, 30]\n[30, 20, 10]", "expected_output": "[10, 20, 30]", "is_hidden": True, "weight": 1.0},
            {"input": "[5, 8, 12]\n[8]", "expected_output": "[8]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Power of Two",
        "description": "Given an integer `n`, return `true` if it is a power of two. Otherwise, return `false`.\n\nAn integer `n` is a power of two if there exists an integer `x` such that $n == 2^x$.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "isPowerOfTwo",
        "parameters": [{"name": "n", "type": "int"}],
        "return_type": "bool",
        "sample_input": "1",
        "sample_output": "true",
        "input_format": "Line 1: integer n",
        "test_cases": [
            {"input": "1", "expected_output": "true", "is_hidden": False, "weight": 1.0},
            {"input": "16", "expected_output": "true", "is_hidden": False, "weight": 1.0},
            {"input": "3", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "0", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "-16", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "2", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "64", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "1024", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "218", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "1073741824", "expected_output": "true", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "First Unique Character in a String",
        "description": "Given a string `s`, find the first non-repeating character in it and return its 0-based index. If it does not exist, return -1.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "firstUniqChar",
        "parameters": [{"name": "s", "type": "string"}],
        "return_type": "int",
        "sample_input": "\"leetcode\"",
        "sample_output": "0",
        "input_format": "Line 1: string s",
        "test_cases": [
            {"input": "\"leetcode\"", "expected_output": "0", "is_hidden": False, "weight": 1.0},
            {"input": "\"loveleetcode\"", "expected_output": "2", "is_hidden": False, "weight": 1.0},
            {"input": "\"aabb\"", "expected_output": "-1", "is_hidden": True, "weight": 1.0},
            {"input": "\"z\"", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "\"aadadaad\"", "expected_output": "-1", "is_hidden": True, "weight": 1.0},
            {"input": "\"swiss\"", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "\"abcdefghijklmnopqrstuvwxyz\"", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "\"abacabad\"", "expected_output": "5", "is_hidden": True, "weight": 1.0},
            {"input": "\"cc\"", "expected_output": "-1", "is_hidden": True, "weight": 1.0},
            {"input": "\"dddccdbba\"", "expected_output": "8", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Find the Index of the First Occurrence in a String",
        "description": "Given two strings `needle` and `haystack`, return the index of the first occurrence of `needle` in `haystack`, or -1 if `needle` is not part of `haystack`.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "strStr",
        "parameters": [{"name": "haystack", "type": "string"}, {"name": "needle", "type": "string"}],
        "return_type": "int",
        "sample_input": "\"sadbutsad\"\n\"sad\"",
        "sample_output": "0",
        "input_format": "Line 1: string haystack\nLine 2: string needle",
        "test_cases": [
            {"input": "\"sadbutsad\"\n\"sad\"", "expected_output": "0", "is_hidden": False, "weight": 1.0},
            {"input": "\"leetcode\"\n\"leeto\"", "expected_output": "-1", "is_hidden": False, "weight": 1.0},
            {"input": "\"hello\"\n\"ll\"", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "\"a\"\n\"a\"", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "\"abc\"\n\"c\"", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "\"mississippi\"\n\"issip\"", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "\"mississippi\"\n\"pi\"", "expected_output": "9", "is_hidden": True, "weight": 1.0},
            {"input": "\"aaa\"\n\"aaaa\"", "expected_output": "-1", "is_hidden": True, "weight": 1.0},
            {"input": "\"testcase\"\n\"case\"", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "\"findinstring\"\n\"in\"", "expected_output": "1", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Jewels and Stones",
        "description": "You're given strings `jewels` representing the types of stones that are jewels, and `stones` representing the stones you have. Each character in `stones` is a type of stone you have. You want to know how many of the stones you have are also jewels.\n\nLetters are case sensitive, so 'a' is considered a different type of stone from 'A'.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "numJewelsInStones",
        "parameters": [{"name": "jewels", "type": "string"}, {"name": "stones", "type": "string"}],
        "return_type": "int",
        "sample_input": "\"aA\"\n\"aAAbbbb\"",
        "sample_output": "3",
        "input_format": "Line 1: string jewels\nLine 2: string stones",
        "test_cases": [
            {"input": "\"aA\"\n\"aAAbbbb\"", "expected_output": "3", "is_hidden": False, "weight": 1.0},
            {"input": "\"z\"\n\"ZZ\"", "expected_output": "0", "is_hidden": False, "weight": 1.0},
            {"input": "\"abc\"\n\"abcdef\"", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "\"\"\n\"abc\"", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "\"xyz\"\n\"\"", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "\"a\"\n\"aaaaa\"", "expected_output": "5", "is_hidden": True, "weight": 1.0},
            {"input": "\"AYZ\"\n\"xyzAYZ\"", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "\"code\"\n\"leetcode\"", "expected_output": "7", "is_hidden": True, "weight": 1.0},
            {"input": "\"X\"\n\"xXxX\"", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "\"QWERTY\"\n\"qwertyQWERTY\"", "expected_output": "6", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Squares of a Sorted Array",
        "description": "Given an integer array `nums` sorted in non-decreasing order, return an array of the squares of each number sorted in non-decreasing order.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "sortedSquares",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int[]",
        "sample_input": "[-4, -1, 0, 3, 10]",
        "sample_output": "[0, 1, 9, 16, 100]",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[-4, -1, 0, 3, 10]", "expected_output": "[0, 1, 9, 16, 100]", "is_hidden": False, "weight": 1.0},
            {"input": "[-7, -3, 2, 3, 11]", "expected_output": "[4, 9, 9, 49, 121]", "is_hidden": False, "weight": 1.0},
            {"input": "[-1]", "expected_output": "[1]", "is_hidden": True, "weight": 1.0},
            {"input": "[0]", "expected_output": "[0]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3]", "expected_output": "[1, 4, 9]", "is_hidden": True, "weight": 1.0},
            {"input": "[-3, -2, -1]", "expected_output": "[1, 4, 9]", "is_hidden": True, "weight": 1.0},
            {"input": "[-5, -4, -3, -2, -1, 0]", "expected_output": "[0, 1, 4, 9, 16, 25]", "is_hidden": True, "weight": 1.0},
            {"input": "[-10, 10]", "expected_output": "[100, 100]", "is_hidden": True, "weight": 1.0},
            {"input": "[-2, 0, 2]", "expected_output": "[0, 4, 4]", "is_hidden": True, "weight": 1.0},
            {"input": "[-100, -50, 0, 50, 100]", "expected_output": "[0, 2500, 2500, 10000, 10000]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Defanging an IP Address",
        "description": "Given a valid (IPv4) IP `address`, return a defanged version of that IP address.\n\nA defanged IP address replaces every period `\".\"` with `\"[.]\"`.",
        "difficulty": QuestionDifficulty.EASY,
        "function_name": "defangIPaddr",
        "parameters": [{"name": "address", "type": "string"}],
        "return_type": "string",
        "sample_input": "\"1.1.1.1\"",
        "sample_output": "\"1[.]1[.]1[.]1\"",
        "input_format": "Line 1: string address",
        "test_cases": [
            {"input": "\"1.1.1.1\"", "expected_output": "\"1[.]1[.]1[.]1\"", "is_hidden": False, "weight": 1.0},
            {"input": "\"255.100.50.0\"", "expected_output": "\"255[.]100[.]50[.]0\"", "is_hidden": False, "weight": 1.0},
            {"input": "\"127.0.0.1\"", "expected_output": "\"127[.]0[.]0[.]1\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"192.168.1.1\"", "expected_output": "\"192[.]168[.]1[.]1\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"10.0.0.1\"", "expected_output": "\"10[.]0[.]0[.]1\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"172.16.254.1\"", "expected_output": "\"172[.]16[.]254[.]1\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"8.8.8.8\"", "expected_output": "\"8[.]8[.]8[.]8\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"8.8.4.4\"", "expected_output": "\"8[.]8[.]4[.]4\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"0.0.0.0\"", "expected_output": "\"0[.]0[.]0[.]0\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"224.0.0.1\"", "expected_output": "\"224[.]0[.]0[.]1\"", "is_hidden": True, "weight": 1.0},
        ]
    }
]
