"""
20 Hard DSA coding problems with typed function signatures and 10 test cases each (2 visible, 8 hidden with edge cases).
"""

from backend.app.models.question import QuestionDifficulty

DSA_HARD_QUESTIONS = [
    {
        "title": "Trapping Rain Water",
        "description": "Given `n` non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "trap",
        "parameters": [{"name": "height", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]",
        "sample_output": "6",
        "input_format": "Line 1: height (int array)",
        "test_cases": [
            {"input": "[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]", "expected_output": "6", "is_hidden": False, "weight": 1.0},
            {"input": "[4, 2, 0, 3, 2, 5]", "expected_output": "9", "is_hidden": False, "weight": 1.0},
            {"input": "[]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[1]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 0, 2]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[3, 0, 0, 2, 0, 4]", "expected_output": "10", "is_hidden": True, "weight": 1.0},
            {"input": "[5, 4, 3, 2, 1]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3, 4, 5]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[5, 2, 1, 2, 1, 5]", "expected_output": "14", "is_hidden": True, "weight": 1.0},
            {"input": "[0, 7, 1, 4, 6]", "expected_output": "7", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Sliding Window Maximum",
        "description": "You are given an array of integers `nums`, there is a sliding window of size `k` which is moving from the very left of the array to the very right. You can only see the `k` numbers in the window. Each time the sliding window moves right by one position.\n\nReturn the max sliding window.",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "maxSlidingWindow",
        "parameters": [{"name": "nums", "type": "int[]"}, {"name": "k", "type": "int"}],
        "return_type": "int[]",
        "sample_input": "[1, 3, -1, -3, 5, 3, 6, 7]\n3",
        "sample_output": "[3, 3, 5, 5, 6, 7]",
        "input_format": "Line 1: nums (int array)\nLine 2: integer k",
        "test_cases": [
            {"input": "[1, 3, -1, -3, 5, 3, 6, 7]\n3", "expected_output": "[3, 3, 5, 5, 6, 7]", "is_hidden": False, "weight": 1.0},
            {"input": "[1]\n1", "expected_output": "[1]", "is_hidden": False, "weight": 1.0},
            {"input": "[1, -1]\n1", "expected_output": "[1, -1]", "is_hidden": True, "weight": 1.0},
            {"input": "[9, 11]\n2", "expected_output": "[11]", "is_hidden": True, "weight": 1.0},
            {"input": "[4, -2]\n2", "expected_output": "[4]", "is_hidden": True, "weight": 1.0},
            {"input": "[7, 2, 4]\n2", "expected_output": "[7, 4]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 3, 1, 2, 0, 5]\n3", "expected_output": "[3, 3, 2, 5]", "is_hidden": True, "weight": 1.0},
            {"input": "[-7, -8, 7, 5, 7, 1, 6, 0]\n4", "expected_output": "[7, 7, 7, 7, 7]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3, 4, 5, 6]\n6", "expected_output": "[6]", "is_hidden": True, "weight": 1.0},
            {"input": "[9, 8, 7, 6, 5]\n1", "expected_output": "[9, 8, 7, 6, 5]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Edit Distance",
        "description": "Given two strings `word1` and `word2`, return the minimum number of operations required to convert `word1` to `word2`.\n\nYou have the following three operations permitted on a word: insert a character, delete a character, or replace a character.",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "minDistance",
        "parameters": [{"name": "word1", "type": "string"}, {"name": "word2", "type": "string"}],
        "return_type": "int",
        "sample_input": "\"horse\"\n\"ros\"",
        "sample_output": "3",
        "input_format": "Line 1: string word1\nLine 2: string word2",
        "test_cases": [
            {"input": "\"horse\"\n\"ros\"", "expected_output": "3", "is_hidden": False, "weight": 1.0},
            {"input": "\"intention\"\n\"execution\"", "expected_output": "5", "is_hidden": False, "weight": 1.0},
            {"input": "\"\"\n\"\"", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "\"a\"\n\"\"", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "\"\"\n\"b\"", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "\"abc\"\n\"abc\"", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "\"ab\"\n\"bc\"", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "\"dinitrophenylhydrazine\"\n\"dimethylhydrazine\"", "expected_output": "6", "is_hidden": True, "weight": 1.0},
            {"input": "\"zoologico\"\n\"zoologist\"", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "\"park\"\n\"spake\"", "expected_output": "3", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Minimum Window Substring",
        "description": "Given two strings `s` and `t` of lengths `m` and `n` respectively, return the minimum window substring of `s` such that every character in `t` (including duplicates) is included in the window. If there is no such substring, return the empty string `\"\"`.",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "minWindow",
        "parameters": [{"name": "s", "type": "string"}, {"name": "t", "type": "string"}],
        "return_type": "string",
        "sample_input": "\"ADOBECODEBANC\"\n\"ABC\"",
        "sample_output": "\"BANC\"",
        "input_format": "Line 1: string s\nLine 2: string t",
        "test_cases": [
            {"input": "\"ADOBECODEBANC\"\n\"ABC\"", "expected_output": "\"BANC\"", "is_hidden": False, "weight": 1.0},
            {"input": "\"a\"\n\"a\"", "expected_output": "\"a\"", "is_hidden": False, "weight": 1.0},
            {"input": "\"a\"\n\"aa\"", "expected_output": "\"\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"ab\"\n\"a\"", "expected_output": "\"a\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"ab\"\n\"b\"", "expected_output": "\"b\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"cabwefgewcwaefgcf\"\n\"cae\"", "expected_output": "\"cwae\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"bba\"\n\"ab\"", "expected_output": "\"ba\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"aaaaaaaaaaaabbq\"\n\"baqqq\"", "expected_output": "\"\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"bdab\"\n\"ab\"", "expected_output": "\"ab\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"aaflslflsldkalskaaa\"\n\"aaa\"", "expected_output": "\"aaa\"", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Largest Rectangle in Histogram",
        "description": "Given an array of integers `heights` representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "largestRectangleArea",
        "parameters": [{"name": "heights", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "[2, 1, 5, 6, 2, 3]",
        "sample_output": "10",
        "input_format": "Line 1: heights (int array)",
        "test_cases": [
            {"input": "[2, 1, 5, 6, 2, 3]", "expected_output": "10", "is_hidden": False, "weight": 1.0},
            {"input": "[2, 4]", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "[]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[1]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[0]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 1, 2]", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "[5, 5, 5, 5]", "expected_output": "20", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3, 4, 5]", "expected_output": "9", "is_hidden": True, "weight": 1.0},
            {"input": "[5, 4, 3, 2, 1]", "expected_output": "9", "is_hidden": True, "weight": 1.0},
            {"input": "[6, 2, 5, 4, 5, 1, 6]", "expected_output": "12", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "First Missing Positive",
        "description": "Given an unsorted integer array `nums`, return the smallest positive integer that is not present in `nums`.\n\nYou must implement an algorithm that runs in $O(n)$ time and uses $O(1)$ auxiliary space.",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "firstMissingPositive",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "[1, 2, 0]",
        "sample_output": "3",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[1, 2, 0]", "expected_output": "3", "is_hidden": False, "weight": 1.0},
            {"input": "[3, 4, -1, 1]", "expected_output": "2", "is_hidden": False, "weight": 1.0},
            {"input": "[7, 8, 9, 11, 12]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[1]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[2]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[-1, -2]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3, 4, 5]", "expected_output": "6", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 1, 1]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 3, 7, 6, 8, -1, -10, 15]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Maximal Rectangle",
        "description": "Given a `rows x cols` binary `matrix` filled with '0's and '1's, find the largest rectangle containing only '1's and return its area.",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "maximalRectangle",
        "parameters": [{"name": "matrix", "type": "string[][]"}],
        "return_type": "int",
        "sample_input": "[[\"1\", \"0\", \"1\", \"0\", \"0\"], [\"1\", \"0\", \"1\", \"1\", \"1\"], [\"1\", \"1\", \"1\", \"1\", \"1\"], [\"1\", \"0\", \"0\", \"1\", \"0\"]]",
        "sample_output": "6",
        "input_format": "Line 1: matrix (2D string array)",
        "test_cases": [
            {"input": "[[\"1\", \"0\", \"1\", \"0\", \"0\"], [\"1\", \"0\", \"1\", \"1\", \"1\"], [\"1\", \"1\", \"1\", \"1\", \"1\"], [\"1\", \"0\", \"0\", \"1\", \"0\"]]", "expected_output": "6", "is_hidden": False, "weight": 1.0},
            {"input": "[[\"0\"]]", "expected_output": "0", "is_hidden": False, "weight": 1.0},
            {"input": "[[\"1\"]]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[[\"0\", \"0\"], [\"0\", \"0\"]]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[[\"1\", \"1\"], [\"1\", \"1\"]]", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "[[\"0\", \"1\"], [\"1\", \"0\"]]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[[\"1\", \"1\", \"1\"], [\"1\", \"1\", \"1\"]]", "expected_output": "6", "is_hidden": True, "weight": 1.0},
            {"input": "[[\"1\", \"0\", \"1\", \"1\", \"1\"], [\"0\", \"1\", \"0\", \"1\", \"0\"], [\"1\", \"1\", \"0\", \"1\", \"1\"], [\"1\", \"1\", \"0\", \"1\", \"1\"], [\"0\", \"1\", \"1\", \"1\", \"1\"]]", "expected_output": "6", "is_hidden": True, "weight": 1.0},
            {"input": "[[\"1\", \"1\", \"0\", \"1\"], [\"1\", \"1\", \"0\", \"1\"], [\"1\", \"1\", \"1\", \"1\"]]", "expected_output": "6", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Longest Valid Parentheses",
        "description": "Given a string containing just the characters '(' and ')', return the length of the longest valid (well-formed) parentheses substring.",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "longestValidParentheses",
        "parameters": [{"name": "s", "type": "string"}],
        "return_type": "int",
        "sample_input": "\"(()\"",
        "sample_output": "2",
        "input_format": "Line 1: string s",
        "test_cases": [
            {"input": "\"(()\"", "expected_output": "2", "is_hidden": False, "weight": 1.0},
            {"input": "\")()())\"", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "\"\"", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "\"(\"", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "\")\"", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "\"()(()\"", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "\"()()\"", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "\"((()))\"", "expected_output": "6", "is_hidden": True, "weight": 1.0},
            {"input": "\"()((()))()\"", "expected_output": "10", "is_hidden": True, "weight": 1.0},
            {"input": "\"(((((\"", "expected_output": "0", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Word Ladder",
        "description": "A transformation sequence from word `beginWord` to word `endWord` using a dictionary `wordList` is a sequence of words `beginWord -> s_1 -> s_2 -> ... -> s_k` such that every adjacent pair of words differs by a single letter, and `s_k == endWord`.\n\nGiven two words, `beginWord` and `endWord`, and a dictionary `wordList`, return the number of words in the shortest transformation sequence from `beginWord` to `endWord`, or 0 if no such sequence exists.",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "ladderLength",
        "parameters": [{"name": "beginWord", "type": "string"}, {"name": "endWord", "type": "string"}, {"name": "wordList", "type": "string[]"}],
        "return_type": "int",
        "sample_input": "\"hit\"\n\"cog\"\n[\"hot\", \"dot\", \"dog\", \"lot\", \"log\", \"cog\"]",
        "sample_output": "5",
        "input_format": "Line 1: string beginWord\nLine 2: string endWord\nLine 3: wordList (string array)",
        "test_cases": [
            {"input": "\"hit\"\n\"cog\"\n[\"hot\", \"dot\", \"dog\", \"lot\", \"log\", \"cog\"]", "expected_output": "5", "is_hidden": False, "weight": 1.0},
            {"input": "\"hit\"\n\"cog\"\n[\"hot\", \"dot\", \"dog\", \"lot\", \"log\"]", "expected_output": "0", "is_hidden": False, "weight": 1.0},
            {"input": "\"a\"\n\"c\"\n[\"a\", \"b\", \"c\"]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "\"hot\"\n\"dog\"\n[\"hot\", \"dog\"]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "\"hot\"\n\"dog\"\n[\"hot\", \"cog\", \"dog\", \"tot\", \"hog\", \"hop\", \"pot\"]", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "\"game\"\n\"thee\"\n[\"frye\", \"heat\", \"tree\", \"thee\", \"game\", \"gate\", \"hate\"]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "\"talk\"\n\"tail\"\n[\"talk\", \"toll\", \"toil\", \"tail\"]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "\"lead\"\n\"gold\"\n[\"load\", \"goad\", \"gold\"]", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "\"kiss\"\n\"tusk\"\n[\"miss\", \"dill\", \"soap\", \"tusk\", \"mast\", \"disk\", \"risk\", \"dusk\", \"kiss\", \"task\"]", "expected_output": "5", "is_hidden": True, "weight": 1.0},
            {"input": "\"red\"\n\"tax\"\n[\"ted\", \"tex\", \"red\", \"tax\", \"tad\", \"den\", \"rex\", \"pee\"]", "expected_output": "4", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "N-Queens",
        "description": "The n-queens puzzle is the problem of placing `n` queens on an `n x n` chessboard such that no two queens attack each other.\n\nGiven an integer `n`, return all distinct solutions to the n-queens puzzle in lexicographical order. Each solution contains a distinct board configuration of the queen's placement, where 'Q' and '.' both indicate a queen and an empty space, respectively.",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "solveNQueens",
        "parameters": [{"name": "n", "type": "int"}],
        "return_type": "string[][]",
        "sample_input": "4",
        "sample_output": "[[\".Q..\", \"...Q\", \"Q...\", \"..Q.\"], [\"..Q.\", \"Q...\", \"...Q\", \".Q..\"]]",
        "input_format": "Line 1: integer n",
        "test_cases": [
            {"input": "4", "expected_output": "[[\".Q..\", \"...Q\", \"Q...\", \"..Q.\"], [\"..Q.\", \"Q...\", \"...Q\", \".Q..\"]]", "is_hidden": False, "weight": 1.0},
            {"input": "1", "expected_output": "[[\"Q\"]]", "is_hidden": False, "weight": 1.0},
            {"input": "2", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
            {"input": "3", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
            {"input": "5", "expected_output": "[[\"Q....\", \"..Q..\", \"....Q\", \".Q...\", \"...Q.\"], [\"Q....\", \"...Q.\", \".Q...\", \"....Q\", \"..Q..\"], [\".Q...\", \"...Q.\", \"Q....\", \"..Q..\", \"....Q\"], [\".Q...\", \"....Q\", \"..Q..\", \"Q....\", \"...Q.\"], [\"..Q..\", \"Q....\", \"...Q.\", \".Q...\", \"....Q\"], [\"..Q..\", \"....Q\", \".Q...\", \"...Q.\", \"Q....\"], [\"...Q.\", \"Q....\", \"..Q..\", \"....Q\", \".Q...\"], [\"...Q.\", \".Q...\", \"....Q\", \"..Q..\", \"Q....\"], [\"....Q\", \".Q...\", \"...Q.\", \"Q....\", \"..Q..\"], [\"....Q\", \"..Q..\", \"Q....\", \"...Q.\", \".Q...\"]]", "is_hidden": True, "weight": 1.0},
            {"input": "6", "expected_output": "[[\".Q....\", \"...Q..\", \".....Q\", \"Q.....\", \"..Q...\", \"....Q.\"], [\"..Q...\", \".....Q\", \".Q....\", \"....Q.\", \"Q.....\", \"...Q..\"], [\"...Q..\", \"Q.....\", \"....Q.\", \".Q....\", \".....Q\", \"..Q...\"], [\"....Q.\", \"..Q...\", \"Q.....\", \".....Q\", \"...Q..\", \".Q....\"]]", "is_hidden": True, "weight": 1.0},
            {"input": "4", "expected_output": "[[\".Q..\", \"...Q\", \"Q...\", \"..Q.\"], [\"..Q.\", \"Q...\", \"...Q\", \".Q..\"]]", "is_hidden": True, "weight": 1.0},
            {"input": "1", "expected_output": "[[\"Q\"]]", "is_hidden": True, "weight": 1.0},
            {"input": "2", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
            {"input": "3", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Regular Expression Matching",
        "description": "Given an input string `s` and a pattern `p`, implement regular expression matching with support for '.' and '*' where:\n- '.' Matches any single character.\n- '*' Matches zero or more of the preceding element.\n\nThe matching should cover the entire input string (not partial).",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "isMatch",
        "parameters": [{"name": "s", "type": "string"}, {"name": "p", "type": "string"}],
        "return_type": "bool",
        "sample_input": "\"aa\"\n\"a\"",
        "sample_output": "false",
        "input_format": "Line 1: string s\nLine 2: string p",
        "test_cases": [
            {"input": "\"aa\"\n\"a\"", "expected_output": "false", "is_hidden": False, "weight": 1.0},
            {"input": "\"aa\"\n\"a*\"", "expected_output": "true", "is_hidden": False, "weight": 1.0},
            {"input": "\"ab\"\n\".*\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"aab\"\n\"c*a*b\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"mississippi\"\n\"mis*is*p*.\"", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "\"\"\n\"\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"a\"\n\"ab*\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"bbbba\"\n\".*a*a\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"ab\"\n\".*c\"", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "\"aaa\"\n\"ab*a*c*a\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Wildcard Matching",
        "description": "Given an input string `s` and a pattern `p`, implement wildcard pattern matching with support for '?' and '*' where:\n- '?' Matches any single character.\n- '*' Matches any sequence of characters (including the empty sequence).\n\nThe matching should cover the entire input string (not partial).",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "isWildcardMatch",
        "parameters": [{"name": "s", "type": "string"}, {"name": "p", "type": "string"}],
        "return_type": "bool",
        "sample_input": "\"aa\"\n\"a\"",
        "sample_output": "false",
        "input_format": "Line 1: string s\nLine 2: string p",
        "test_cases": [
            {"input": "\"aa\"\n\"a\"", "expected_output": "false", "is_hidden": False, "weight": 1.0},
            {"input": "\"aa\"\n\"*\"", "expected_output": "true", "is_hidden": False, "weight": 1.0},
            {"input": "\"cb\"\n\"?a\"", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "\"adceb\"\n\"*a*b\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"acdcb\"\n\"a*c?b\"", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "\"\"\n\"*\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"\"\n\"\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"abc\"\n\"*abc\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"b\"\n\"?*?\"", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "\"ho\"\n\"**ho\"", "expected_output": "true", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Distinct Subsequences",
        "description": "Given two strings `s` and `t`, return the number of distinct subsequences of `s` which equals `t`.",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "numDistinct",
        "parameters": [{"name": "s", "type": "string"}, {"name": "t", "type": "string"}],
        "return_type": "int",
        "sample_input": "\"rabbbit\"\n\"rabbit\"",
        "sample_output": "3",
        "input_format": "Line 1: string s\nLine 2: string t",
        "test_cases": [
            {"input": "\"rabbbit\"\n\"rabbit\"", "expected_output": "3", "is_hidden": False, "weight": 1.0},
            {"input": "\"babgbag\"\n\"bag\"", "expected_output": "5", "is_hidden": False, "weight": 1.0},
            {"input": "\"\"\n\"a\"", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "\"a\"\n\"\"", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "\"a\"\n\"a\"", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "\"aaa\"\n\"a\"", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "\"aaa\"\n\"aa\"", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "\"aabdbaeeeadcbbdaefebeebedababbbbbaecceeedcbf\"\n\"bd\"", "expected_output": "18", "is_hidden": True, "weight": 1.0},
            {"input": "\"ananas\"\n\"ana\"", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "\"daacaedaceacabbaabd\"\n\"dace\"", "expected_output": "1", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Candy Distribution",
        "description": "There are `n` children standing in a line. Each child is assigned a rating value given in the integer array `ratings`.\n\nYou are giving candies to these children subjected to the following requirements:\n- Each child must have at least one candy.\n- Children with a higher rating get more candies than their neighbors.\n\nReturn the minimum number of candies you need to have to distribute the candies to the children.",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "candy",
        "parameters": [{"name": "ratings", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "[1, 0, 2]",
        "sample_output": "5",
        "input_format": "Line 1: ratings (int array)",
        "test_cases": [
            {"input": "[1, 0, 2]", "expected_output": "5", "is_hidden": False, "weight": 1.0},
            {"input": "[1, 2, 2]", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "[1]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2]", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 1]", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 3, 2, 2, 1]", "expected_output": "7", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 87, 87, 87, 2, 1]", "expected_output": "13", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 3, 4, 5, 2]", "expected_output": "11", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 6, 10, 8, 7, 3, 2]", "expected_output": "18", "is_hidden": True, "weight": 1.0},
            {"input": "[29, 51, 87, 87, 72, 12]", "expected_output": "12", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Longest Increasing Path in a Matrix",
        "description": "Given an `m x n` integers matrix, return the length of the longest increasing path in matrix.\n\nFrom each cell, you can either move in four directions: left, right, up, or down. You may not move diagonally or move outside the boundary.",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "longestIncreasingPath",
        "parameters": [{"name": "matrix", "type": "int[][]"}],
        "return_type": "int",
        "sample_input": "[[9, 9, 4], [6, 6, 8], [2, 1, 1]]",
        "sample_output": "4",
        "input_format": "Line 1: matrix (2D int array)",
        "test_cases": [
            {"input": "[[9, 9, 4], [6, 6, 8], [2, 1, 1]]", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "[[3, 4, 5], [3, 2, 6], [2, 2, 1]]", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "[[1]]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 2], [3, 4]]", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 2, 3], [6, 5, 4], [7, 8, 9]]", "expected_output": "9", "is_hidden": True, "weight": 1.0},
            {"input": "[[7, 8, 9], [9, 7, 6], [7, 2, 3]]", "expected_output": "6", "is_hidden": True, "weight": 1.0},
            {"input": "[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]", "expected_output": "10", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 1], [1, 1]]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[[2, 1], [1, 2]]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[[3, 2, 1], [4, 5, 6], [9, 8, 7]]", "expected_output": "9", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Burst Balloons",
        "description": "You are given `n` balloons, indexed from `0` to `n - 1`. Each balloon is painted with a number on it represented by an array `nums`. You are asked to burst all the balloons.\n\nIf you burst the $i^{th}$ balloon, you will get `nums[i - 1] * nums[i] * nums[i + 1]` coins. If `i - 1` or `i + 1` goes out of bounds of the array, then treat it as if there is a balloon with a 1 painted on it.\n\nReturn the maximum coins you can collect by bursting the balloons wisely.",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "maxCoins",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "[3, 1, 5, 8]",
        "sample_output": "167",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[3, 1, 5, 8]", "expected_output": "167", "is_hidden": False, "weight": 1.0},
            {"input": "[1, 5]", "expected_output": "10", "is_hidden": False, "weight": 1.0},
            {"input": "[]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[7]", "expected_output": "7", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3]", "expected_output": "12", "is_hidden": True, "weight": 1.0},
            {"input": "[8, 2, 6, 8]", "expected_output": "480", "is_hidden": True, "weight": 1.0},
            {"input": "[9, 76, 64, 21]", "expected_output": "107870", "is_hidden": True, "weight": 1.0},
            {"input": "[3, 4, 5]", "expected_output": "77", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 3, 7, 9, 1]", "expected_output": "260", "is_hidden": True, "weight": 1.0},
            {"input": "[3, 1, 5]", "expected_output": "35", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Dungeon Game",
        "description": "The demons had captured the princess and imprisoned her in the bottom-right corner of a `dungeon`. The knight was initially positioned in the top-left room and must fight his way through `dungeon` to rescue the princess.\n\nThe knight has an initial health point represented by a positive integer. If at any point his health point drops to 0 or below, he dies immediately.\n\nSome rooms contain demons that decrease the knight's health, and other rooms contain magic orbs that increase his health. Return the knight's minimum initial health so that he can rescue the princess.",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "calculateMinimumHP",
        "parameters": [{"name": "dungeon", "type": "int[][]"}],
        "return_type": "int",
        "sample_input": "[[-2, -3, 3], [-5, -10, 1], [10, 30, -5]]",
        "sample_output": "7",
        "input_format": "Line 1: dungeon (2D int array)",
        "test_cases": [
            {"input": "[[-2, -3, 3], [-5, -10, 1], [10, 30, -5]]", "expected_output": "7", "is_hidden": False, "weight": 1.0},
            {"input": "[[0]]", "expected_output": "1", "is_hidden": False, "weight": 1.0},
            {"input": "[[-5]]", "expected_output": "6", "is_hidden": True, "weight": 1.0},
            {"input": "[[5]]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, -3, 3], [0, -2, 0], [-3, -3, -3]]", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "[[-1, 1]]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, -1]]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[[-200]]", "expected_output": "201", "is_hidden": True, "weight": 1.0},
            {"input": "[[0, 0, 0], [0, 0, 0]]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[[-3, 5]]", "expected_output": "4", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Best Time to Buy and Sell Stock IV",
        "description": "You are given an integer array `prices` where `prices[i]` is the price of a given stock on the $i^{th}$ day, and an integer `k`.\n\nFind the maximum profit you can achieve. You may complete at most `k` transactions: i.e. you may buy at most `k` times and sell at most `k` times.",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "maxProfitIV",
        "parameters": [{"name": "k", "type": "int"}, {"name": "prices", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "2\n[2, 4, 1]",
        "sample_output": "2",
        "input_format": "Line 1: integer k\nLine 2: prices (int array)",
        "test_cases": [
            {"input": "2\n[2, 4, 1]", "expected_output": "2", "is_hidden": False, "weight": 1.0},
            {"input": "2\n[3, 2, 6, 5, 0, 3]", "expected_output": "7", "is_hidden": False, "weight": 1.0},
            {"input": "2\n[]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "1\n[1]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "0\n[1, 2, 3, 4, 5]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "1\n[1, 2, 3, 4, 5]", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "2\n[1, 2, 4, 2, 5, 7, 2, 4, 9, 0]", "expected_output": "13", "is_hidden": True, "weight": 1.0},
            {"input": "4\n[1, 2, 4, 2, 5, 7, 2, 4, 9, 0]", "expected_output": "15", "is_hidden": True, "weight": 1.0},
            {"input": "2\n[7, 6, 4, 3, 1]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "2\n[3, 3, 5, 0, 0, 3, 1, 4]", "expected_output": "6", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Russian Doll Envelopes",
        "description": "You are given a 2D array of integers `envelopes` where `envelopes[i] = [w_i, h_i]` represents the width and the height of an envelope.\n\nOne envelope can fit into another if and only if both the width and height of one envelope are strictly greater than the other envelope's width and height.\n\nReturn the maximum number of envelopes you can Russian doll (i.e., put one inside the other).",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "maxEnvelopes",
        "parameters": [{"name": "envelopes", "type": "int[][]"}],
        "return_type": "int",
        "sample_input": "[[5, 4], [6, 4], [6, 7], [2, 3]]",
        "sample_output": "3",
        "input_format": "Line 1: envelopes (2D int array)",
        "test_cases": [
            {"input": "[[5, 4], [6, 4], [6, 7], [2, 3]]", "expected_output": "3", "is_hidden": False, "weight": 1.0},
            {"input": "[[1, 1], [1, 1], [1, 1]]", "expected_output": "1", "is_hidden": False, "weight": 1.0},
            {"input": "[]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 1]]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[[2, 3], [5, 4], [6, 7], [6, 4]]", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 3], [3, 5], [6, 7], [6, 8], [8, 4], [9, 5]]", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "[[10, 8], [1, 12], [6, 15], [2, 18]]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[[4, 5], [4, 6], [6, 7], [2, 3], [1, 1]]", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 2], [2, 3], [3, 4], [4, 5], [5, 6]]", "expected_output": "5", "is_hidden": True, "weight": 1.0},
            {"input": "[[3, 4], [12, 2], [12, 15], [30, 50]]", "expected_output": "3", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Find Substring with Concatenation of All Words",
        "description": "You are given a string `s` and an array of strings `words`. All the strings of `words` are of the same length.\n\nA concatenated substring in `s` is a substring that contains all the strings of any permutation of `words` concatenated.\n\nReturn the starting indices of all the concatenated substrings in `s` in ascending order.",
        "difficulty": QuestionDifficulty.HARD,
        "function_name": "findSubstring",
        "parameters": [{"name": "s", "type": "string"}, {"name": "words", "type": "string[]"}],
        "return_type": "int[]",
        "sample_input": "\"barfoothefoobarman\"\n[\"foo\", \"bar\"]",
        "sample_output": "[0, 9]",
        "input_format": "Line 1: string s\nLine 2: words (string array)",
        "test_cases": [
            {"input": "\"barfoothefoobarman\"\n[\"foo\", \"bar\"]", "expected_output": "[0, 9]", "is_hidden": False, "weight": 1.0},
            {"input": "\"wordgoodgoodgoodbestword\"\n[\"word\", \"good\", \"best\", \"word\"]", "expected_output": "[]", "is_hidden": False, "weight": 1.0},
            {"input": "\"barfoofoobarthefoobarman\"\n[\"bar\", \"foo\", \"the\"]", "expected_output": "[6, 9, 12]", "is_hidden": True, "weight": 1.0},
            {"input": "\"wordgoodgoodgoodbestword\"\n[\"word\", \"good\", \"best\", \"good\"]", "expected_output": "[8]", "is_hidden": True, "weight": 1.0},
            {"input": "\"lingmindraboofooowingdingbarrwingmonkeypoundcake\"\n[\"fooo\", \"barr\", \"wing\", \"ding\", \"wing\"]", "expected_output": "[13]", "is_hidden": True, "weight": 1.0},
            {"input": "\"a\"\n[\"a\"]", "expected_output": "[0]", "is_hidden": True, "weight": 1.0},
            {"input": "\"a\"\n[\"b\"]", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
            {"input": "\"aaaaaaaaaaaaaa\"\n[\"aa\", \"aa\"]", "expected_output": "[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]", "is_hidden": True, "weight": 1.0},
            {"input": "\"abababab\"\n[\"a\", \"b\", \"a\"]", "expected_output": "[0, 2, 4]", "is_hidden": True, "weight": 1.0},
            {"input": "\"mississippi\"\n[\"is\"]", "expected_output": "[1, 4]", "is_hidden": True, "weight": 1.0},
        ]
    }
]
