"""
40 Medium DSA coding problems with typed function signatures and 10 test cases each (2 visible, 8 hidden with edge cases).
"""

from backend.app.models.question import QuestionDifficulty

DSA_MEDIUM_QUESTIONS = [
    {
        "title": "Longest Substring Without Repeating Characters",
        "description": "Given a string `s`, find the length of the longest substring without repeating characters.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "lengthOfLongestSubstring",
        "parameters": [{"name": "s", "type": "string"}],
        "return_type": "int",
        "sample_input": "\"abcabcbb\"",
        "sample_output": "3",
        "input_format": "Line 1: string s",
        "test_cases": [
            {"input": "\"abcabcbb\"", "expected_output": "3", "is_hidden": False, "weight": 1.0},
            {"input": "\"bbbbb\"", "expected_output": "1", "is_hidden": False, "weight": 1.0},
            {"input": "\"pwwkew\"", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "\"\"", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "\" \"", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "\"au\"", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "\"dvdf\"", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "\"anviaj\"", "expected_output": "5", "is_hidden": True, "weight": 1.0},
            {"input": "\"abcdefghijklmnopqrstuvwxyz\"", "expected_output": "26", "is_hidden": True, "weight": 1.0},
            {"input": "\"tmmzuxt\"", "expected_output": "5", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "3Sum Zero",
        "description": "Given an integer array `nums`, return all the triplets `[nums[i], nums[j], nums[k]]` such that `i != j`, `i != k`, and `j != k`, and `nums[i] + nums[j] + nums[k] == 0`.\n\nNotice that the solution set must not contain duplicate triplets. Each triplet should be sorted, and the outer array should be sorted.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "threeSum",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int[][]",
        "sample_input": "[-1, 0, 1, 2, -1, -4]",
        "sample_output": "[[-1, -1, 2], [-1, 0, 1]]",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[-1, 0, 1, 2, -1, -4]", "expected_output": "[[-1, -1, 2], [-1, 0, 1]]", "is_hidden": False, "weight": 1.0},
            {"input": "[0, 1, 1]", "expected_output": "[]", "is_hidden": False, "weight": 1.0},
            {"input": "[0, 0, 0]", "expected_output": "[[0, 0, 0]]", "is_hidden": True, "weight": 1.0},
            {"input": "[]", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
            {"input": "[0]", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
            {"input": "[-2, 0, 1, 1, 2]", "expected_output": "[[-2, 0, 2], [-2, 1, 1]]", "is_hidden": True, "weight": 1.0},
            {"input": "[-1, 0, 1, 0]", "expected_output": "[[-1, 0, 1]]", "is_hidden": True, "weight": 1.0},
            {"input": "[-4, -2, -2, -2, 0, 1, 2, 2, 2, 3, 3, 4, 4, 6, 6]", "expected_output": "[[-4, -2, 6], [-4, 0, 4], [-4, 1, 3], [-4, 2, 2], [-2, -2, 4], [-2, 0, 2]]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, -2, -1]", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
            {"input": "[3, 0, -2, -1, 1, 2]", "expected_output": "[[-2, -1, 3], [-2, 0, 2], [-1, 0, 1]]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Container With Most Water",
        "description": "You are given an integer array `height` of length `n`. There are `n` vertical lines drawn such that the two endpoints of the $i^{th}$ line are `(i, 0)` and `(i, height[i])`.\n\nFind two lines that together with the x-axis form a container, such that the container contains the most water. Return the maximum amount of water a container can store.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "maxArea",
        "parameters": [{"name": "height", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "[1, 8, 6, 2, 5, 4, 8, 3, 7]",
        "sample_output": "49",
        "input_format": "Line 1: height (int array)",
        "test_cases": [
            {"input": "[1, 8, 6, 2, 5, 4, 8, 3, 7]", "expected_output": "49", "is_hidden": False, "weight": 1.0},
            {"input": "[1, 1]", "expected_output": "1", "is_hidden": False, "weight": 1.0},
            {"input": "[4, 3, 2, 1, 4]", "expected_output": "16", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 1]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 3, 4, 5, 18, 17, 6]", "expected_output": "17", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 4, 3]", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 1, 1, 1, 1, 1]", "expected_output": "5", "is_hidden": True, "weight": 1.0},
            {"input": "[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]", "expected_output": "25", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 8, 100, 2, 100, 4, 8, 3, 7]", "expected_output": "200", "is_hidden": True, "weight": 1.0},
            {"input": "[100, 100]", "expected_output": "100", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Group Anagrams",
        "description": "Given an array of strings `strs`, group the anagrams together. You can return the answer in sorted order.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "groupAnagrams",
        "parameters": [{"name": "strs", "type": "string[]"}],
        "return_type": "string[][]",
        "sample_input": "[\"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\"]",
        "sample_output": "[[\"bat\"], [\"nat\", \"tan\"], [\"ate\", \"eat\", \"tea\"]]",
        "input_format": "Line 1: strs (string array)",
        "test_cases": [
            {"input": "[\"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\"]", "expected_output": "[[\"bat\"], [\"nat\", \"tan\"], [\"ate\", \"eat\", \"tea\"]]", "is_hidden": False, "weight": 1.0},
            {"input": "[\"\"]", "expected_output": "[[\"\"]]", "is_hidden": False, "weight": 1.0},
            {"input": "[\"a\"]", "expected_output": "[[\"a\"]]", "is_hidden": True, "weight": 1.0},
            {"input": "[\"ab\", \"ba\"]", "expected_output": "[[\"ab\", \"ba\"]]", "is_hidden": True, "weight": 1.0},
            {"input": "[\"abc\", \"def\", \"ghi\"]", "expected_output": "[[\"abc\"], [\"def\"], [\"ghi\"]]", "is_hidden": True, "weight": 1.0},
            {"input": "[\"listen\", \"silent\", \"enlist\"]", "expected_output": "[[\"enlist\", \"listen\", \"silent\"]]", "is_hidden": True, "weight": 1.0},
            {"input": "[\"rat\", \"tar\", \"art\", \"car\"]", "expected_output": "[[\"art\", \"rat\", \"tar\"], [\"car\"]]", "is_hidden": True, "weight": 1.0},
            {"input": "[\"a\", \"b\", \"a\"]", "expected_output": "[[\"a\", \"a\"], [\"b\"]]", "is_hidden": True, "weight": 1.0},
            {"input": "[]", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
            {"input": "[\"stop\", \"pots\", \"spot\", \"post\", \"opts\"]", "expected_output": "[[\"opts\", \"post\", \"pots\", \"spot\", \"stop\"]]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Top K Frequent Elements",
        "description": "Given an integer array `nums` and an integer `k`, return the `k` most frequent elements in ascending order.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "topKFrequent",
        "parameters": [{"name": "nums", "type": "int[]"}, {"name": "k", "type": "int"}],
        "return_type": "int[]",
        "sample_input": "[1, 1, 1, 2, 2, 3]\n2",
        "sample_output": "[1, 2]",
        "input_format": "Line 1: nums (int array)\nLine 2: k (int)",
        "test_cases": [
            {"input": "[1, 1, 1, 2, 2, 3]\n2", "expected_output": "[1, 2]", "is_hidden": False, "weight": 1.0},
            {"input": "[1]\n1", "expected_output": "[1]", "is_hidden": False, "weight": 1.0},
            {"input": "[1, 2]\n2", "expected_output": "[1, 2]", "is_hidden": True, "weight": 1.0},
            {"input": "[4, 1, -1, 2, -1, 2, 3]\n2", "expected_output": "[-1, 2]", "is_hidden": True, "weight": 1.0},
            {"input": "[5, 5, 5, 5, 2, 2, 3, 3, 3]\n1", "expected_output": "[5]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3, 4, 5, 6, 7]\n3", "expected_output": "[1, 2, 3]", "is_hidden": True, "weight": 1.0},
            {"input": "[-1, -1, -2, -2, -2, -3]\n1", "expected_output": "[-2]", "is_hidden": True, "weight": 1.0},
            {"input": "[10, 20, 10, 20, 30, 10]\n2", "expected_output": "[10, 20]", "is_hidden": True, "weight": 1.0},
            {"input": "[3, 0, 1, 0]\n1", "expected_output": "[0]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 5]\n1", "expected_output": "[5]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Product of Array Except Self",
        "description": "Given an integer array `nums`, return an array `answer` such that `answer[i]` is equal to the product of all the elements of `nums` except `nums[i]`.\n\nYou must write an algorithm that runs in $O(n)$ time and without using the division operation.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "productExceptSelf",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int[]",
        "sample_input": "[1, 2, 3, 4]",
        "sample_output": "[24, 12, 8, 6]",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[1, 2, 3, 4]", "expected_output": "[24, 12, 8, 6]", "is_hidden": False, "weight": 1.0},
            {"input": "[-1, 1, 0, -3, 3]", "expected_output": "[0, 0, 9, 0, 0]", "is_hidden": False, "weight": 1.0},
            {"input": "[2, 3]", "expected_output": "[3, 2]", "is_hidden": True, "weight": 1.0},
            {"input": "[0, 0]", "expected_output": "[0, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 0]", "expected_output": "[0, 1]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 1, 1, 1]", "expected_output": "[1, 1, 1, 1]", "is_hidden": True, "weight": 1.0},
            {"input": "[-1, -1, -1]", "expected_output": "[1, 1, 1]", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 2, 2, 2, 2]", "expected_output": "[16, 16, 16, 16, 16]", "is_hidden": True, "weight": 1.0},
            {"input": "[4, 5, 1, 8, 2]", "expected_output": "[80, 64, 320, 40, 160]", "is_hidden": True, "weight": 1.0},
            {"input": "[9, 0, -2]", "expected_output": "[0, -18, 0]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Longest Consecutive Sequence",
        "description": "Given an unsorted array of integers `nums`, return the length of the longest consecutive elements sequence.\n\nYou must write an algorithm that runs in $O(n)$ time.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "longestConsecutive",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "[100, 4, 200, 1, 3, 2]",
        "sample_output": "4",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[100, 4, 200, 1, 3, 2]", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "[0, 3, 7, 2, 5, 8, 4, 6, 0, 1]", "expected_output": "9", "is_hidden": False, "weight": 1.0},
            {"input": "[]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[1]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 0, 1]", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "[9, 1, 4, 7, 3, -1, 0, 5, 8, -1, 6]", "expected_output": "7", "is_hidden": True, "weight": 1.0},
            {"input": "[-5, -4, -3, -2, -1, 0, 1, 2]", "expected_output": "8", "is_hidden": True, "weight": 1.0},
            {"input": "[10, 20, 30, 40]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]", "expected_output": "10", "is_hidden": True, "weight": 1.0},
            {"input": "[4, 0, -4, -2, 2, 5, 2, 0, -8, -8, -8, -8, -1, 7, 4, 5, 5, -4, 6, 6, -3]", "expected_output": "5", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Two Sum II - Input Array Is Sorted",
        "description": "Given a 1-indexed array of integers `numbers` that is already sorted in non-decreasing order, find two numbers such that they add up to a specific `target` number. Return the indices of the two numbers, `[index1, index2]`, added by one as an integer array `[index1, index2]` of length 2.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "twoSumSorted",
        "parameters": [{"name": "numbers", "type": "int[]"}, {"name": "target", "type": "int"}],
        "return_type": "int[]",
        "sample_input": "[2, 7, 11, 15]\n9",
        "sample_output": "[1, 2]",
        "input_format": "Line 1: numbers (int array)\nLine 2: target (int)",
        "test_cases": [
            {"input": "[2, 7, 11, 15]\n9", "expected_output": "[1, 2]", "is_hidden": False, "weight": 1.0},
            {"input": "[2, 3, 4]\n6", "expected_output": "[1, 3]", "is_hidden": False, "weight": 1.0},
            {"input": "[-1, 0]\n-1", "expected_output": "[1, 2]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3, 4, 4, 9, 56, 90]\n8", "expected_output": "[4, 5]", "is_hidden": True, "weight": 1.0},
            {"input": "[5, 25, 75]\n100", "expected_output": "[2, 3]", "is_hidden": True, "weight": 1.0},
            {"input": "[-3, 3, 4, 90]\n0", "expected_output": "[1, 2]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 3, 5, 7, 9, 11]\n16", "expected_output": "[4, 5]", "is_hidden": True, "weight": 1.0},
            {"input": "[-10, -8, -2, 1, 2, 5]\n-1", "expected_output": "[3, 4]", "is_hidden": True, "weight": 1.0},
            {"input": "[0, 0, 3, 4]\n0", "expected_output": "[1, 2]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3, 4, 5, 6, 7]\n11", "expected_output": "[4, 7]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Coin Change Minimum",
        "description": "You are given an integer array `coins` representing coins of different denominations and an integer `amount` representing a total amount of money.\n\nReturn the fewest number of coins that you need to make up that amount. If that amount of money cannot be made up by any combination of the coins, return -1.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "coinChange",
        "parameters": [{"name": "coins", "type": "int[]"}, {"name": "amount", "type": "int"}],
        "return_type": "int",
        "sample_input": "[1, 2, 5]\n11",
        "sample_output": "3",
        "input_format": "Line 1: coins (int array)\nLine 2: amount (int)",
        "test_cases": [
            {"input": "[1, 2, 5]\n11", "expected_output": "3", "is_hidden": False, "weight": 1.0},
            {"input": "[2]\n3", "expected_output": "-1", "is_hidden": False, "weight": 1.0},
            {"input": "[1]\n0", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[1]\n1", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[1]\n2", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 3, 4, 5]\n7", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 5, 10, 1]\n27", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "[186, 419, 83, 408]\n6249", "expected_output": "20", "is_hidden": True, "weight": 1.0},
            {"input": "[3, 7, 405, 436]\n8839", "expected_output": "25", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 4, 6, 8, 10]\n15", "expected_output": "-1", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Merge Intervals",
        "description": "Given an array of `intervals` where `intervals[i] = [start_i, end_i]`, merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "merge",
        "parameters": [{"name": "intervals", "type": "int[][]"}],
        "return_type": "int[][]",
        "sample_input": "[[1, 3], [2, 6], [8, 10], [15, 18]]",
        "sample_output": "[[1, 6], [8, 10], [15, 18]]",
        "input_format": "Line 1: intervals (2D int array)",
        "test_cases": [
            {"input": "[[1, 3], [2, 6], [8, 10], [15, 18]]", "expected_output": "[[1, 6], [8, 10], [15, 18]]", "is_hidden": False, "weight": 1.0},
            {"input": "[[1, 4], [4, 5]]", "expected_output": "[[1, 5]]", "is_hidden": False, "weight": 1.0},
            {"input": "[]", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 4]]", "expected_output": "[[1, 4]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 4], [2, 3]]", "expected_output": "[[1, 4]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 4], [0, 4]]", "expected_output": "[[0, 4]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 4], [0, 1]]", "expected_output": "[[0, 4]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[2, 3], [4, 5], [6, 7], [8, 9], [1, 10]]", "expected_output": "[[1, 10]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[2, 3], [5, 5], [2, 2], [3, 4], [3, 4]]", "expected_output": "[[2, 4], [5, 5]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 10], [2, 3], [4, 5], [6, 7], [8, 9]]", "expected_output": "[[1, 10]]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Insert Interval",
        "description": "You are given an array of non-overlapping intervals `intervals` where `intervals[i] = [start_i, end_i]` sorted in ascending order by `start_i`. You are also given an interval `newInterval = [start, end]` that represents the start and end of another interval.\n\nInsert `newInterval` into `intervals` such that `intervals` is still sorted in ascending order and still does not have any overlapping intervals (merge overlapping intervals if necessary).",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "insert",
        "parameters": [{"name": "intervals", "type": "int[][]"}, {"name": "newInterval", "type": "int[]"}],
        "return_type": "int[][]",
        "sample_input": "[[1, 3], [6, 9]]\n[2, 5]",
        "sample_output": "[[1, 5], [6, 9]]",
        "input_format": "Line 1: intervals (2D int array)\nLine 2: newInterval (int array)",
        "test_cases": [
            {"input": "[[1, 3], [6, 9]]\n[2, 5]", "expected_output": "[[1, 5], [6, 9]]", "is_hidden": False, "weight": 1.0},
            {"input": "[[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]]\n[4, 8]", "expected_output": "[[1, 2], [3, 10], [12, 16]]", "is_hidden": False, "weight": 1.0},
            {"input": "[]\n[5, 7]", "expected_output": "[[5, 7]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 5]]\n[2, 3]", "expected_output": "[[1, 5]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 5]]\n[2, 7]", "expected_output": "[[1, 7]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 5]]\n[6, 8]", "expected_output": "[[1, 5], [6, 8]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[3, 5]]\n[1, 2]", "expected_output": "[[1, 2], [3, 5]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 5], [6, 8]]\n[0, 9]", "expected_output": "[[0, 9]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 5], [9, 12]]\n[0, 4]", "expected_output": "[[0, 5], [9, 12]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 3], [4, 6], [8, 10]]\n[3, 8]", "expected_output": "[[1, 10]]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Daily Temperatures",
        "description": "Given an array of integers `temperatures` represents the daily temperatures, return an array `answer` such that `answer[i]` is the number of days you have to wait after the $i^{th}$ day to get a warmer temperature. If there is no future day for which this is possible, keep `answer[i] == 0` instead.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "dailyTemperatures",
        "parameters": [{"name": "temperatures", "type": "int[]"}],
        "return_type": "int[]",
        "sample_input": "[73, 74, 75, 71, 69, 72, 76, 73]",
        "sample_output": "[1, 1, 4, 2, 1, 1, 0, 0]",
        "input_format": "Line 1: temperatures (int array)",
        "test_cases": [
            {"input": "[73, 74, 75, 71, 69, 72, 76, 73]", "expected_output": "[1, 1, 4, 2, 1, 1, 0, 0]", "is_hidden": False, "weight": 1.0},
            {"input": "[30, 40, 50, 60]", "expected_output": "[1, 1, 1, 0]", "is_hidden": False, "weight": 1.0},
            {"input": "[30, 60, 90]", "expected_output": "[1, 1, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[89, 62, 70, 58, 47, 47, 46, 76, 100, 70]", "expected_output": "[8, 1, 5, 4, 3, 2, 1, 1, 0, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[50, 50, 50, 50]", "expected_output": "[0, 0, 0, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[100]", "expected_output": "[0]", "is_hidden": True, "weight": 1.0},
            {"input": "[90, 80, 70, 60, 50]", "expected_output": "[0, 0, 0, 0, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[30, 31, 32, 33, 34]", "expected_output": "[1, 1, 1, 1, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[40, 35, 45, 30, 50]", "expected_output": "[2, 1, 2, 1, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[70, 71, 70, 71, 70, 71]", "expected_output": "[1, 0, 1, 0, 1, 0]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Search in Rotated Sorted Array",
        "description": "Given the array `nums` after the possible rotation and an integer `target`, return the index of `target` if it is in `nums`, or -1 if it is not in `nums`.\n\nYou must write an algorithm with $O(\\log n)$ runtime complexity.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "searchRotated",
        "parameters": [{"name": "nums", "type": "int[]"}, {"name": "target", "type": "int"}],
        "return_type": "int",
        "sample_input": "[4, 5, 6, 7, 0, 1, 2]\n0",
        "sample_output": "4",
        "input_format": "Line 1: nums (int array)\nLine 2: target (int)",
        "test_cases": [
            {"input": "[4, 5, 6, 7, 0, 1, 2]\n0", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "[4, 5, 6, 7, 0, 1, 2]\n3", "expected_output": "-1", "is_hidden": False, "weight": 1.0},
            {"input": "[1]\n0", "expected_output": "-1", "is_hidden": True, "weight": 1.0},
            {"input": "[1]\n1", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 3]\n3", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[3, 1]\n1", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[5, 1, 3]\n5", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[4, 5, 6, 7, 8, 1, 2, 3]\n8", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "[6, 7, 1, 2, 3, 4, 5]\n6", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[6, 7, 1, 2, 3, 4, 5]\n3", "expected_output": "4", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Find Minimum in Rotated Sorted Array",
        "description": "Suppose an array of length `n` sorted in ascending order is rotated between 1 and `n` times. Given the sorted rotated array `nums` of unique elements, return the minimum element of this array.\n\nYou must write an algorithm that runs in $O(\\log n)$ time.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "findMin",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "[3, 4, 5, 1, 2]",
        "sample_output": "1",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[3, 4, 5, 1, 2]", "expected_output": "1", "is_hidden": False, "weight": 1.0},
            {"input": "[4, 5, 6, 7, 0, 1, 2]", "expected_output": "0", "is_hidden": False, "weight": 1.0},
            {"input": "[11, 13, 15, 17]", "expected_output": "11", "is_hidden": True, "weight": 1.0},
            {"input": "[1]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 1]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[3, 1, 2]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[5, 1, 2, 3, 4]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[10, 20, 30, 40, 50, 5]", "expected_output": "5", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 3, 4, 5, 1]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[-2, -1, -5, -4, -3]", "expected_output": "-5", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Subsets",
        "description": "Given an integer array `nums` of unique elements, return all possible subsets (the power set).\n\nThe solution set must not contain duplicate subsets. Return the solution sorted.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "subsets",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int[][]",
        "sample_input": "[1, 2, 3]",
        "sample_output": "[[], [1], [1, 2], [1, 2, 3], [1, 3], [2], [2, 3], [3]]",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[1, 2, 3]", "expected_output": "[[], [1], [1, 2], [1, 2, 3], [1, 3], [2], [2, 3], [3]]", "is_hidden": False, "weight": 1.0},
            {"input": "[0]", "expected_output": "[[], [0]]", "is_hidden": False, "weight": 1.0},
            {"input": "[]", "expected_output": "[[]]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2]", "expected_output": "[[], [1], [1, 2], [2]]", "is_hidden": True, "weight": 1.0},
            {"input": "[5]", "expected_output": "[[], [5]]", "is_hidden": True, "weight": 1.0},
            {"input": "[9, 0]", "expected_output": "[[], [0], [0, 9], [9]]", "is_hidden": True, "weight": 1.0},
            {"input": "[3, 2, 1]", "expected_output": "[[], [1], [1, 2], [1, 2, 3], [1, 3], [2], [2, 3], [3]]", "is_hidden": True, "weight": 1.0},
            {"input": "[-1, 1]", "expected_output": "[[], [-1], [-1, 1], [1]]", "is_hidden": True, "weight": 1.0},
            {"input": "[4, 5, 6]", "expected_output": "[[], [4], [4, 5], [4, 5, 6], [4, 6], [5], [5, 6], [6]]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3, 4]", "expected_output": "[[], [1], [1, 2], [1, 2, 3], [1, 2, 3, 4], [1, 2, 4], [1, 3], [1, 3, 4], [1, 4], [2], [2, 3], [2, 3, 4], [2, 4], [3], [3, 4], [4]]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Permutations",
        "description": "Given an array `nums` of distinct integers, return all the possible permutations in sorted order.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "permute",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int[][]",
        "sample_input": "[1, 2, 3]",
        "sample_output": "[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[1, 2, 3]", "expected_output": "[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]", "is_hidden": False, "weight": 1.0},
            {"input": "[0, 1]", "expected_output": "[[0, 1], [1, 0]]", "is_hidden": False, "weight": 1.0},
            {"input": "[1]", "expected_output": "[[1]]", "is_hidden": True, "weight": 1.0},
            {"input": "[]", "expected_output": "[[]]", "is_hidden": True, "weight": 1.0},
            {"input": "[-1, 1]", "expected_output": "[[-1, 1], [1, -1]]", "is_hidden": True, "weight": 1.0},
            {"input": "[3, 2, 1]", "expected_output": "[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 5]", "expected_output": "[[2, 5], [5, 2]]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 4]", "expected_output": "[[1, 2, 4], [1, 4, 2], [2, 1, 4], [2, 4, 1], [4, 1, 2], [4, 2, 1]]", "is_hidden": True, "weight": 1.0},
            {"input": "[0, 2, 4]", "expected_output": "[[0, 2, 4], [0, 4, 2], [2, 0, 4], [2, 4, 0], [4, 0, 2], [4, 2, 0]]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3, 4]", "expected_output": "[[1, 2, 3, 4], [1, 2, 4, 3], [1, 3, 2, 4], [1, 3, 4, 2], [1, 4, 2, 3], [1, 4, 3, 2], [2, 1, 3, 4], [2, 1, 4, 3], [2, 3, 1, 4], [2, 3, 4, 1], [2, 4, 1, 3], [2, 4, 3, 1], [3, 1, 2, 4], [3, 1, 4, 2], [3, 2, 1, 4], [3, 2, 4, 1], [3, 4, 1, 2], [3, 4, 2, 1], [4, 1, 2, 3], [4, 1, 3, 2], [4, 2, 1, 3], [4, 2, 3, 1], [4, 3, 1, 2], [4, 3, 2, 1]]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Combination Sum",
        "description": "Given an array of distinct integers `candidates` and a target integer `target`, return a list of all unique combinations of `candidates` where the chosen numbers sum to `target`. You may return the combinations in any order.\n\nThe same number may be chosen from `candidates` an unlimited number of times.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "combinationSum",
        "parameters": [{"name": "candidates", "type": "int[]"}, {"name": "target", "type": "int"}],
        "return_type": "int[][]",
        "sample_input": "[2, 3, 6, 7]\n7",
        "sample_output": "[[2, 2, 3], [7]]",
        "input_format": "Line 1: candidates (int array)\nLine 2: target (int)",
        "test_cases": [
            {"input": "[2, 3, 6, 7]\n7", "expected_output": "[[2, 2, 3], [7]]", "is_hidden": False, "weight": 1.0},
            {"input": "[2, 3, 5]\n8", "expected_output": "[[2, 2, 2, 2], [2, 3, 3], [3, 5]]", "is_hidden": False, "weight": 1.0},
            {"input": "[2]\n1", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
            {"input": "[1]\n1", "expected_output": "[[1]]", "is_hidden": True, "weight": 1.0},
            {"input": "[1]\n2", "expected_output": "[[1, 1]]", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 4, 6]\n5", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
            {"input": "[3, 5, 8]\n11", "expected_output": "[[3, 3, 5], [3, 8]]", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 3, 7]\n7", "expected_output": "[[2, 2, 3], [7]]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2]\n4", "expected_output": "[[1, 1, 1, 1], [1, 1, 2], [1, 2, 2], [2, 2]]", "is_hidden": True, "weight": 1.0},
            {"input": "[7, 3, 2]\n18", "expected_output": "[[2, 2, 2, 2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 3, 3], [2, 2, 2, 2, 3, 7], [2, 2, 2, 3, 3, 3, 3], [2, 2, 7, 7], [2, 3, 3, 3, 7], [3, 3, 3, 3, 3, 3], [7, 7, 7]]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Letter Combinations of a Phone Number",
        "description": "Given a string containing digits from `2-9` inclusive, return all possible letter combinations that the number could represent. Return the answer in sorted order.\n\nA mapping of digits to letters corresponds to telephone buttons: 2:abc, 3:def, 4:ghi, 5:jkl, 6:mno, 7:pqrs, 8:tuv, 9:wxyz.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "letterCombinations",
        "parameters": [{"name": "digits", "type": "string"}],
        "return_type": "string[]",
        "sample_input": "\"23\"",
        "sample_output": "[\"ad\", \"ae\", \"af\", \"bd\", \"be\", \"bf\", \"cd\", \"ce\", \"cf\"]",
        "input_format": "Line 1: string digits",
        "test_cases": [
            {"input": "\"23\"", "expected_output": "[\"ad\", \"ae\", \"af\", \"bd\", \"be\", \"bf\", \"cd\", \"ce\", \"cf\"]", "is_hidden": False, "weight": 1.0},
            {"input": "\"\"", "expected_output": "[]", "is_hidden": False, "weight": 1.0},
            {"input": "\"2\"", "expected_output": "[\"a\", \"b\", \"c\"]", "is_hidden": True, "weight": 1.0},
            {"input": "\"7\"", "expected_output": "[\"p\", \"q\", \"r\", \"s\"]", "is_hidden": True, "weight": 1.0},
            {"input": "\"9\"", "expected_output": "[\"w\", \"x\", \"y\", \"z\"]", "is_hidden": True, "weight": 1.0},
            {"input": "\"45\"", "expected_output": "[\"gj\", \"gk\", \"gl\", \"hj\", \"hk\", \"hl\", \"ij\", \"ik\", \"il\"]", "is_hidden": True, "weight": 1.0},
            {"input": "\"89\"", "expected_output": "[\"tw\", \"tx\", \"ty\", \"tz\", \"uw\", \"ux\", \"uy\", \"uz\", \"vw\", \"vx\", \"vy\", \"vz\"]", "is_hidden": True, "weight": 1.0},
            {"input": "\"22\"", "expected_output": "[\"aa\", \"ab\", \"ac\", \"ba\", \"bb\", \"bc\", \"ca\", \"cb\", \"cc\"]", "is_hidden": True, "weight": 1.0},
            {"input": "\"78\"", "expected_output": "[\"pt\", \"pu\", \"pv\", \"qt\", \"qu\", \"qv\", \"rt\", \"ru\", \"rv\", \"st\", \"su\", \"sv\"]", "is_hidden": True, "weight": 1.0},
            {"input": "\"234\"", "expected_output": "[\"adg\", \"adh\", \"adi\", \"aeg\", \"aeh\", \"aei\", \"afg\", \"afh\", \"afi\", \"bdg\", \"bdh\", \"bdi\", \"beg\", \"beh\", \"bei\", \"bfg\", \"bfh\", \"bfi\", \"cdg\", \"cdh\", \"cdi\", \"ceg\", \"ceh\", \"cei\", \"cfg\", \"cfh\", \"cfi\"]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Generate Parentheses",
        "description": "Given `n` pairs of parentheses, write a function to generate all combinations of well-formed parentheses in lexicographical order.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "generateParenthesis",
        "parameters": [{"name": "n", "type": "int"}],
        "return_type": "string[]",
        "sample_input": "3",
        "sample_output": "[\"((()))\", \"(()())\", \"(())()\", \"()(())\", \"()()()\"]",
        "input_format": "Line 1: integer n",
        "test_cases": [
            {"input": "3", "expected_output": "[\"((()))\", \"(()())\", \"(())()\", \"()(())\", \"()()()\"]", "is_hidden": False, "weight": 1.0},
            {"input": "1", "expected_output": "[\"()\"]", "is_hidden": False, "weight": 1.0},
            {"input": "0", "expected_output": "[\"\"]", "is_hidden": True, "weight": 1.0},
            {"input": "2", "expected_output": "[\"(())\", \"()()\"]", "is_hidden": True, "weight": 1.0},
            {"input": "4", "expected_output": "[\"(((())))\", \"((()()))\", \"((())())\", \"((()))()\", \"(()(()))\", \"(()()())\", \"(()())()\", \"(())(())\", \"(())()()\", \"()((()))\", \"()(()())\", \"()(())()\", \"()()(())\", \"()()()()\"]", "is_hidden": True, "weight": 1.0},
            {"input": "5", "expected_output": "[\"((((()))))\", \"(((()())))\", \"(((())()))\", \"(((()))())\", \"(((())))()\", \"((()(())))\", \"((()()()))\", \"((()())())\", \"((())(()))\", \"((())()())\", \"((()))(())\", \"((()))()()\", \"(()((())))\", \"(()(()()))\", \"(()(())())\", \"(()((())))()\", \"(()()(()))\", \"(()()()())\", \"(()()())()\", \"(()())(())\", \"(()())()()\", \"(())(()())\", \"(())(())()\", \"(())()(())\", \"(())()()()\", \"()(((())))\", \"()((()()))\", \"()((())())\", \"()((()))()\", \"()(()(()))\", \"()(()()())\", \"()(()())()\", \"()(())(())\", \"()(())()()\", \"()()((()))\", \"()()(()())\", \"()()(())()\", \"()()()(())\", \"()()()()()\"]", "is_hidden": True, "weight": 1.0},
            {"input": "2", "expected_output": "[\"(())\", \"()()\"]", "is_hidden": True, "weight": 1.0},
            {"input": "1", "expected_output": "[\"()\"]", "is_hidden": True, "weight": 1.0},
            {"input": "3", "expected_output": "[\"((()))\", \"(()())\", \"(())()\", \"()(())\", \"()()()\"]", "is_hidden": True, "weight": 1.0},
            {"input": "4", "expected_output": "[\"(((())))\", \"((()()))\", \"((())())\", \"((()))()\", \"(()(()))\", \"(()()())\", \"(()())()\", \"(())(())\", \"(())()()\", \"()((()))\", \"()(()())\", \"()(())()\", \"()()(())\", \"()()()()\"]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "House Robber",
        "description": "You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed. Adjacent houses have security systems connected, and it will automatically contact the police if two adjacent houses were broken into on the same night.\n\nGiven an integer array `nums` representing the amount of money of each house, return the maximum amount of money you can rob tonight without alerting the police.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "rob",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "[1, 2, 3, 1]",
        "sample_output": "4",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[1, 2, 3, 1]", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "[2, 7, 9, 3, 1]", "expected_output": "12", "is_hidden": False, "weight": 1.0},
            {"input": "[0]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[5]", "expected_output": "5", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 1, 1, 2]", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "[100, 1, 1, 100]", "expected_output": "200", "is_hidden": True, "weight": 1.0},
            {"input": "[4, 1, 2, 7, 5, 3, 1]", "expected_output": "14", "is_hidden": True, "weight": 1.0},
            {"input": "[10, 20, 30, 40, 50, 60]", "expected_output": "90", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 4, 8, 9, 9, 3]", "expected_output": "19", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 3, 1, 3, 100]", "expected_output": "104", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "House Robber II",
        "description": "All houses at this place are arranged in a circle. That means the first house is the neighbor of the last one. Meanwhile, adjacent houses have a security system connected, and it will automatically contact the police if two adjacent houses were broken into on the same night.\n\nGiven an integer array `nums` representing the amount of money of each house, return the maximum amount of money you can rob tonight without alerting the police.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "rob2",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "[2, 3, 2]",
        "sample_output": "3",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[2, 3, 2]", "expected_output": "3", "is_hidden": False, "weight": 1.0},
            {"input": "[1, 2, 3, 1]", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "[1, 2, 3]", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "[1]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[200, 3, 140, 20, 10]", "expected_output": "340", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 3, 1, 3, 100]", "expected_output": "103", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 7, 9, 2]", "expected_output": "10", "is_hidden": True, "weight": 1.0},
            {"input": "[4, 1, 2, 7, 5, 3, 1]", "expected_output": "14", "is_hidden": True, "weight": 1.0},
            {"input": "[10, 2, 3, 15, 20, 1, 2]", "expected_output": "33", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Longest Palindromic Substring",
        "description": "Given a string `s`, return the longest palindromic substring in `s`. If there are multiple palindromic substrings with the same maximum length, return the first one.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "longestPalindrome",
        "parameters": [{"name": "s", "type": "string"}],
        "return_type": "string",
        "sample_input": "\"babad\"",
        "sample_output": "\"bab\"",
        "input_format": "Line 1: string s",
        "test_cases": [
            {"input": "\"babad\"", "expected_output": "\"bab\"", "is_hidden": False, "weight": 1.0},
            {"input": "\"cbbd\"", "expected_output": "\"bb\"", "is_hidden": False, "weight": 1.0},
            {"input": "\"a\"", "expected_output": "\"a\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"ac\"", "expected_output": "\"a\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"racecar\"", "expected_output": "\"racecar\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"noon\"", "expected_output": "\"noon\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"forgeeksskeegfor\"", "expected_output": "\"geeksskeeg\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"banana\"", "expected_output": "\"anana\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"abacdfgdcaba\"", "expected_output": "\"aba\"", "is_hidden": True, "weight": 1.0},
            {"input": "\"aaaa\"", "expected_output": "\"aaaa\"", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Palindromic Substrings Count",
        "description": "Given a string `s`, return the number of palindromic substrings in it.\n\nA string is a palindrome when it reads the same backward as forward. A substring is a contiguous sequence of characters within the string.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "countSubstrings",
        "parameters": [{"name": "s", "type": "string"}],
        "return_type": "int",
        "sample_input": "\"abc\"",
        "sample_output": "3",
        "input_format": "Line 1: string s",
        "test_cases": [
            {"input": "\"abc\"", "expected_output": "3", "is_hidden": False, "weight": 1.0},
            {"input": "\"aaa\"", "expected_output": "6", "is_hidden": False, "weight": 1.0},
            {"input": "\"a\"", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "\"aba\"", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "\"abccba\"", "expected_output": "9", "is_hidden": True, "weight": 1.0},
            {"input": "\"racecar\"", "expected_output": "10", "is_hidden": True, "weight": 1.0},
            {"input": "\"noon\"", "expected_output": "6", "is_hidden": True, "weight": 1.0},
            {"input": "\"aaaaa\"", "expected_output": "15", "is_hidden": True, "weight": 1.0},
            {"input": "\"leetcode\"", "expected_output": "9", "is_hidden": True, "weight": 1.0},
            {"input": "\"bb\"", "expected_output": "3", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Decode Ways",
        "description": "A message containing letters from A-Z can be encoded into numbers using the mapping: 'A' -> \"1\", 'B' -> \"2\", ... 'Z' -> \"26\".\n\nGiven a string `s` containing only digits, return the number of ways to decode it.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "numDecodings",
        "parameters": [{"name": "s", "type": "string"}],
        "return_type": "int",
        "sample_input": "\"12\"",
        "sample_output": "2",
        "input_format": "Line 1: string s",
        "test_cases": [
            {"input": "\"12\"", "expected_output": "2", "is_hidden": False, "weight": 1.0},
            {"input": "\"226\"", "expected_output": "3", "is_hidden": False, "weight": 1.0},
            {"input": "\"06\"", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "\"10\"", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "\"27\"", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "\"0\"", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "\"2101\"", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "\"111111\"", "expected_output": "13", "is_hidden": True, "weight": 1.0},
            {"input": "\"2611055971756562\"", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "\"100\"", "expected_output": "0", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Unique Paths",
        "description": "There is a robot on an `m x n` grid. The robot is initially located at the top-left corner `(0, 0)`. The robot tries to move to the bottom-right corner `(m - 1, n - 1)`. The robot can only move either down or right at any point in time.\n\nGiven the two integers `m` and `n`, return the number of possible unique paths that the robot can take to reach the bottom-right corner.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "uniquePaths",
        "parameters": [{"name": "m", "type": "int"}, {"name": "n", "type": "int"}],
        "return_type": "int",
        "sample_input": "3\n7",
        "sample_output": "28",
        "input_format": "Line 1: integer m\nLine 2: integer n",
        "test_cases": [
            {"input": "3\n7", "expected_output": "28", "is_hidden": False, "weight": 1.0},
            {"input": "3\n2", "expected_output": "3", "is_hidden": False, "weight": 1.0},
            {"input": "1\n1", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "1\n10", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "10\n1", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "2\n2", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "3\n3", "expected_output": "6", "is_hidden": True, "weight": 1.0},
            {"input": "7\n3", "expected_output": "28", "is_hidden": True, "weight": 1.0},
            {"input": "5\n5", "expected_output": "70", "is_hidden": True, "weight": 1.0},
            {"input": "10\n10", "expected_output": "48620", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Jump Game",
        "description": "You are given an integer array `nums`. You are initially positioned at the array's first index, and each element in the array represents your maximum jump length at that position.\n\nReturn `true` if you can reach the last index, or `false` otherwise.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "canJump",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "bool",
        "sample_input": "[2, 3, 1, 1, 4]",
        "sample_output": "true",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[2, 3, 1, 1, 4]", "expected_output": "true", "is_hidden": False, "weight": 1.0},
            {"input": "[3, 2, 1, 0, 4]", "expected_output": "false", "is_hidden": False, "weight": 1.0},
            {"input": "[0]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 0, 1, 0]", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 0, 0]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 5, 0, 0]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "[0, 2, 3]", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 1, 1, 1, 1]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "[5, 9, 3, 2, 1, 0, 2, 3, 3, 1, 0, 0]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Jump Game II",
        "description": "You are given a 0-indexed array of integers `nums` of length `n`. You are initially positioned at `nums[0]`. Each element `nums[i]` represents the maximum length of a forward jump from index `i`.\n\nReturn the minimum number of jumps to reach `nums[n - 1]`. You can assume that you can always reach the last index.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "jump",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "[2, 3, 1, 1, 4]",
        "sample_output": "2",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[2, 3, 1, 1, 4]", "expected_output": "2", "is_hidden": False, "weight": 1.0},
            {"input": "[2, 3, 0, 1, 4]", "expected_output": "2", "is_hidden": False, "weight": 1.0},
            {"input": "[0]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 1, 1, 1]", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "[3, 2, 1]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 1, 1, 1]", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 1, 0]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[7, 0, 9, 6, 9, 6, 1, 7, 9, 0, 1, 2, 9, 0, 3]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[5, 4, 0, 0, 0, 0, 0]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Rotting Oranges",
        "description": "You are given an `m x n` grid where each cell can have one of three values: 0 representing an empty cell, 1 representing a fresh orange, or 2 representing a rotten orange.\n\nEvery minute, any fresh orange that is 4-directionally adjacent to a rotten orange becomes rotten.\n\nReturn the minimum number of minutes that must elapse until no cell has a fresh orange. If this is impossible, return -1.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "orangesRotting",
        "parameters": [{"name": "grid", "type": "int[][]"}],
        "return_type": "int",
        "sample_input": "[[2, 1, 1], [1, 1, 0], [0, 1, 1]]",
        "sample_output": "4",
        "input_format": "Line 1: grid (2D int array)",
        "test_cases": [
            {"input": "[[2, 1, 1], [1, 1, 0], [0, 1, 1]]", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "[[2, 1, 1], [0, 1, 1], [1, 0, 1]]", "expected_output": "-1", "is_hidden": False, "weight": 1.0},
            {"input": "[[0, 2]]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[[1]]", "expected_output": "-1", "is_hidden": True, "weight": 1.0},
            {"input": "[[0]]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[[2]]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[[2, 2], [1, 1], [0, 0], [2, 0]]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[[2, 1, 1], [1, 1, 1], [0, 1, 2]]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 2]]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[[0, 0, 0], [0, 0, 0]]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Non-overlapping Intervals",
        "description": "Given an array of intervals `intervals` where `intervals[i] = [start_i, end_i]`, return the minimum number of intervals you need to remove to make the rest of the intervals non-overlapping.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "eraseOverlapIntervals",
        "parameters": [{"name": "intervals", "type": "int[][]"}],
        "return_type": "int",
        "sample_input": "[[1, 2], [2, 3], [3, 4], [1, 3]]",
        "sample_output": "1",
        "input_format": "Line 1: intervals (2D int array)",
        "test_cases": [
            {"input": "[[1, 2], [2, 3], [3, 4], [1, 3]]", "expected_output": "1", "is_hidden": False, "weight": 1.0},
            {"input": "[[1, 2], [1, 2], [1, 2]]", "expected_output": "2", "is_hidden": False, "weight": 1.0},
            {"input": "[[1, 2], [2, 3]]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 2]]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 100], [11, 22], [1, 11], [2, 12]]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[[0, 2], [1, 3], [2, 4], [3, 5], [4, 6]]", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 10], [2, 3], [3, 4], [4, 5]]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[[0, 1], [3, 4], [1, 2]]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 2], [2, 4], [1, 3]]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Longest Increasing Subsequence",
        "description": "Given an integer array `nums`, return the length of the longest strictly increasing subsequence.\n\nA subsequence is an array that can be derived from another array by deleting some or no elements without changing the order of the remaining elements.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "lengthOfLIS",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int",
        "sample_input": "[10, 9, 2, 5, 3, 7, 101, 18]",
        "sample_output": "4",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[10, 9, 2, 5, 3, 7, 101, 18]", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "[0, 1, 0, 3, 2, 3]", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "[7, 7, 7, 7, 7, 7, 7]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[1]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 3, 6, 7, 9, 4, 10, 5, 6]", "expected_output": "6", "is_hidden": True, "weight": 1.0},
            {"input": "[4, 10, 4, 3, 8, 9]", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3, 4, 5]", "expected_output": "5", "is_hidden": True, "weight": 1.0},
            {"input": "[3, 5, 6, 2, 5, 4, 19, 5, 6, 7, 12]", "expected_output": "6", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 2]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Partition Equal Subset Sum",
        "description": "Given an integer array `nums`, return `true` if you can partition the array into two subsets such that the sum of the elements in both subsets is equal or `false` otherwise.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "canPartition",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "bool",
        "sample_input": "[1, 5, 11, 5]",
        "sample_output": "true",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[1, 5, 11, 5]", "expected_output": "true", "is_hidden": False, "weight": 1.0},
            {"input": "[1, 2, 3, 5]", "expected_output": "false", "is_hidden": False, "weight": 1.0},
            {"input": "[1]", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 1]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 2, 2, 2]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 5]", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "[14, 9, 8, 4, 3, 2]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 2, 3, 5]", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "[100]", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 2, 3, 4, 5, 6, 7]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Kth Largest Element in an Array",
        "description": "Given an integer array `nums` and an integer `k`, return the $k^{th}$ largest element in the array.\n\nNote that it is the $k^{th}$ largest element in the sorted order, not the $k^{th}$ distinct element.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "findKthLargest",
        "parameters": [{"name": "nums", "type": "int[]"}, {"name": "k", "type": "int"}],
        "return_type": "int",
        "sample_input": "[3, 2, 1, 5, 6, 4]\n2",
        "sample_output": "5",
        "input_format": "Line 1: nums (int array)\nLine 2: k (int)",
        "test_cases": [
            {"input": "[3, 2, 1, 5, 6, 4]\n2", "expected_output": "5", "is_hidden": False, "weight": 1.0},
            {"input": "[3, 2, 3, 1, 2, 4, 5, 5, 6]\n4", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "[1]\n1", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 1]\n1", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 1]\n2", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[-1, -1]\n2", "expected_output": "-1", "is_hidden": True, "weight": 1.0},
            {"input": "[7, 6, 5, 4, 3, 2, 1]\n5", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "[99, 99]\n1", "expected_output": "99", "is_hidden": True, "weight": 1.0},
            {"input": "[5, 2, 4, 1, 3, 6, 0]\n4", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "[10, 20, 30, 40, 50]\n1", "expected_output": "50", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Sort Colors",
        "description": "Given an array `nums` with `n` objects colored red, white, or blue, sort them in-place so that objects of the same color are adjacent, with the colors in the order red, white, and blue.\n\nWe will use the integers 0, 1, and 2 to represent the color red, white, and blue, respectively. Return the sorted array.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "sortColors",
        "parameters": [{"name": "nums", "type": "int[]"}],
        "return_type": "int[]",
        "sample_input": "[2, 0, 2, 1, 1, 0]",
        "sample_output": "[0, 0, 1, 1, 2, 2]",
        "input_format": "Line 1: nums (int array)",
        "test_cases": [
            {"input": "[2, 0, 2, 1, 1, 0]", "expected_output": "[0, 0, 1, 1, 2, 2]", "is_hidden": False, "weight": 1.0},
            {"input": "[2, 0, 1]", "expected_output": "[0, 1, 2]", "is_hidden": False, "weight": 1.0},
            {"input": "[0]", "expected_output": "[0]", "is_hidden": True, "weight": 1.0},
            {"input": "[1]", "expected_output": "[1]", "is_hidden": True, "weight": 1.0},
            {"input": "[2]", "expected_output": "[2]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 0]", "expected_output": "[0, 1]", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 1, 0]", "expected_output": "[0, 1, 2]", "is_hidden": True, "weight": 1.0},
            {"input": "[0, 0, 0]", "expected_output": "[0, 0, 0]", "is_hidden": True, "weight": 1.0},
            {"input": "[1, 1, 1]", "expected_output": "[1, 1, 1]", "is_hidden": True, "weight": 1.0},
            {"input": "[2, 2, 2]", "expected_output": "[2, 2, 2]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Spiral Matrix",
        "description": "Given an `m x n` `matrix`, return all elements of the `matrix` in spiral order.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "spiralOrder",
        "parameters": [{"name": "matrix", "type": "int[][]"}],
        "return_type": "int[]",
        "sample_input": "[[1, 2, 3], [4, 5, 6], [7, 8, 9]]",
        "sample_output": "[1, 2, 3, 6, 9, 8, 7, 4, 5]",
        "input_format": "Line 1: matrix (2D int array)",
        "test_cases": [
            {"input": "[[1, 2, 3], [4, 5, 6], [7, 8, 9]]", "expected_output": "[1, 2, 3, 6, 9, 8, 7, 4, 5]", "is_hidden": False, "weight": 1.0},
            {"input": "[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]", "expected_output": "[1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7]", "is_hidden": False, "weight": 1.0},
            {"input": "[[1]]", "expected_output": "[1]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 2], [3, 4]]", "expected_output": "[1, 2, 4, 3]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 2, 3]]", "expected_output": "[1, 2, 3]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1], [2], [3]]", "expected_output": "[1, 2, 3]", "is_hidden": True, "weight": 1.0},
            {"input": "[[2, 5, 8], [4, 0, -1]]", "expected_output": "[2, 5, 8, -1, 0, 4]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 2], [3, 4], [5, 6]]", "expected_output": "[1, 2, 4, 6, 5, 3]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 2, 3, 4, 5]]", "expected_output": "[1, 2, 3, 4, 5]", "is_hidden": True, "weight": 1.0},
            {"input": "[[7], [9], [6]]", "expected_output": "[7, 9, 6]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Rotate Image Matrix",
        "description": "You are given an `n x n` 2D `matrix` representing an image, rotate the image by 90 degrees (clockwise). Return the rotated matrix.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "rotateImage",
        "parameters": [{"name": "matrix", "type": "int[][]"}],
        "return_type": "int[][]",
        "sample_input": "[[1, 2, 3], [4, 5, 6], [7, 8, 9]]",
        "sample_output": "[[7, 4, 1], [8, 5, 2], [9, 6, 3]]",
        "input_format": "Line 1: matrix (2D int array)",
        "test_cases": [
            {"input": "[[1, 2, 3], [4, 5, 6], [7, 8, 9]]", "expected_output": "[[7, 4, 1], [8, 5, 2], [9, 6, 3]]", "is_hidden": False, "weight": 1.0},
            {"input": "[[5, 1, 9, 11], [2, 4, 8, 10], [13, 3, 6, 7], [15, 14, 12, 16]]", "expected_output": "[[15, 13, 2, 5], [14, 3, 4, 1], [12, 6, 8, 9], [16, 7, 10, 11]]", "is_hidden": False, "weight": 1.0},
            {"input": "[[1]]", "expected_output": "[[1]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 2], [3, 4]]", "expected_output": "[[3, 1], [4, 2]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[0, 0], [0, 0]]", "expected_output": "[[0, 0], [0, 0]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 0, 0], [0, 1, 0], [0, 0, 1]]", "expected_output": "[[0, 0, 1], [0, 1, 0], [1, 0, 0]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[-1, -2], [-3, -4]]", "expected_output": "[[-3, -1], [-4, -2]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 2, 3], [3, 2, 1], [2, 1, 3]]", "expected_output": "[[2, 3, 1], [1, 2, 2], [3, 1, 3]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[4, 8], [3, 6]]", "expected_output": "[[3, 4], [6, 8]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]", "expected_output": "[[13, 9, 5, 1], [14, 10, 6, 2], [15, 11, 7, 3], [16, 12, 8, 4]]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Set Matrix Zeroes",
        "description": "Given an `m x n` integer matrix `matrix`, if an element is 0, set its entire row and column to 0's. Return the modified matrix.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "setZeroes",
        "parameters": [{"name": "matrix", "type": "int[][]"}],
        "return_type": "int[][]",
        "sample_input": "[[1, 1, 1], [1, 0, 1], [1, 1, 1]]",
        "sample_output": "[[1, 0, 1], [0, 0, 0], [1, 0, 1]]",
        "input_format": "Line 1: matrix (2D int array)",
        "test_cases": [
            {"input": "[[1, 1, 1], [1, 0, 1], [1, 1, 1]]", "expected_output": "[[1, 0, 1], [0, 0, 0], [1, 0, 1]]", "is_hidden": False, "weight": 1.0},
            {"input": "[[0, 1, 2, 0], [3, 4, 5, 2], [1, 3, 1, 5]]", "expected_output": "[[0, 0, 0, 0], [0, 4, 5, 0], [0, 3, 1, 0]]", "is_hidden": False, "weight": 1.0},
            {"input": "[[1]]", "expected_output": "[[1]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[0]]", "expected_output": "[[0]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 0]]", "expected_output": "[[0, 0]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[0], [1]]", "expected_output": "[[0], [0]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 2, 3], [4, 5, 6]]", "expected_output": "[[1, 2, 3], [4, 5, 6]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[0, 0], [0, 0]]", "expected_output": "[[0, 0], [0, 0]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[2, 1, 3], [0, 5, 6], [7, 8, 9]]", "expected_output": "[[0, 1, 3], [0, 0, 0], [0, 8, 9]]", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 2, 0, 4], [5, 6, 7, 8]]", "expected_output": "[[0, 0, 0, 0], [5, 6, 0, 8]]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Minimum Path Sum",
        "description": "Given a `m x n` `grid` filled with non-negative numbers, find a path from top left to bottom right, which minimizes the sum of all numbers along its path. You can only move either down or right at any point in time.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "minPathSum",
        "parameters": [{"name": "grid", "type": "int[][]"}],
        "return_type": "int",
        "sample_input": "[[1, 3, 1], [1, 5, 1], [4, 2, 1]]",
        "sample_output": "7",
        "input_format": "Line 1: grid (2D int array)",
        "test_cases": [
            {"input": "[[1, 3, 1], [1, 5, 1], [4, 2, 1]]", "expected_output": "7", "is_hidden": False, "weight": 1.0},
            {"input": "[[1, 2, 3], [4, 5, 6]]", "expected_output": "12", "is_hidden": False, "weight": 1.0},
            {"input": "[[1]]", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 2], [1, 1]]", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "[[0, 0], [0, 0]]", "expected_output": "0", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 2, 5], [3, 2, 1]]", "expected_output": "6", "is_hidden": True, "weight": 1.0},
            {"input": "[[5, 4, 2], [8, 2, 1], [1, 3, 4]]", "expected_output": "13", "is_hidden": True, "weight": 1.0},
            {"input": "[[9, 1, 4, 8]]", "expected_output": "22", "is_hidden": True, "weight": 1.0},
            {"input": "[[1], [2], [3], [4]]", "expected_output": "10", "is_hidden": True, "weight": 1.0},
            {"input": "[[1, 1, 1], [1, 1, 1], [1, 1, 1]]", "expected_output": "5", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Word Break",
        "description": "Given a string `s` and a dictionary of strings `wordDict`, return `true` if `s` can be segmented into a space-separated sequence of one or more dictionary words.\n\nNote that the same word in the dictionary may be reused multiple times in the segmentation.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "wordBreak",
        "parameters": [{"name": "s", "type": "string"}, {"name": "wordDict", "type": "string[]"}],
        "return_type": "bool",
        "sample_input": "\"leetcode\"\n[\"leet\", \"code\"]",
        "sample_output": "true",
        "input_format": "Line 1: string s\nLine 2: wordDict (string array)",
        "test_cases": [
            {"input": "\"leetcode\"\n[\"leet\", \"code\"]", "expected_output": "true", "is_hidden": False, "weight": 1.0},
            {"input": "\"applepenapple\"\n[\"apple\", \"pen\"]", "expected_output": "true", "is_hidden": False, "weight": 1.0},
            {"input": "\"catsandog\"\n[\"cats\", \"dog\", \"sand\", \"and\", \"cat\"]", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "\"a\"\n[\"a\"]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"a\"\n[\"b\"]", "expected_output": "false", "is_hidden": True, "weight": 1.0},
            {"input": "\"cars\"\n[\"car\", \"ca\", \"rs\"]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"bb\"\n[\"a\", \"b\", \"bbb\", \"bbbb\"]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"abcd\"\n[\"a\", \"abc\", \"b\", \"cd\"]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"goalspecial\"\n[\"go\", \"goal\", \"goals\", \"special\"]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
            {"input": "\"aaaaaaa\"\n[\"aaaa\", \"aaa\"]", "expected_output": "true", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Find All Anagrams in a String",
        "description": "Given two strings `s` and `p`, return an array of all the start indices of `p`'s anagrams in `s`. You may return the answer in ascending order.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "findAnagrams",
        "parameters": [{"name": "s", "type": "string"}, {"name": "p", "type": "string"}],
        "return_type": "int[]",
        "sample_input": "\"cbaebabacd\"\n\"abc\"",
        "sample_output": "[0, 6]",
        "input_format": "Line 1: string s\nLine 2: string p",
        "test_cases": [
            {"input": "\"cbaebabacd\"\n\"abc\"", "expected_output": "[0, 6]", "is_hidden": False, "weight": 1.0},
            {"input": "\"abab\"\n\"ab\"", "expected_output": "[0, 1, 2]", "is_hidden": False, "weight": 1.0},
            {"input": "\"a\"\n\"a\"", "expected_output": "[0]", "is_hidden": True, "weight": 1.0},
            {"input": "\"a\"\n\"b\"", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
            {"input": "\"ab\"\n\"ba\"", "expected_output": "[0]", "is_hidden": True, "weight": 1.0},
            {"input": "\"baa\"\n\"aa\"", "expected_output": "[1]", "is_hidden": True, "weight": 1.0},
            {"input": "\"aaaaa\"\n\"aa\"", "expected_output": "[0, 1, 2, 3]", "is_hidden": True, "weight": 1.0},
            {"input": "\"abcdefg\"\n\"xyz\"", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
            {"input": "\"acdcaeccde\"\n\"c\"", "expected_output": "[1, 3, 5, 6]", "is_hidden": True, "weight": 1.0},
            {"input": "\"af\"\n\"be\"", "expected_output": "[]", "is_hidden": True, "weight": 1.0},
        ]
    },
    {
        "title": "Longest Repeating Character Replacement",
        "description": "You are given a string `s` and an integer `k`. You can choose any character of the string and change it to any other uppercase English character. You can perform this operation at most `k` times.\n\nReturn the length of the longest substring containing the same letter you can get after performing the above operations.",
        "difficulty": QuestionDifficulty.MEDIUM,
        "function_name": "characterReplacement",
        "parameters": [{"name": "s", "type": "string"}, {"name": "k", "type": "int"}],
        "return_type": "int",
        "sample_input": "\"ABAB\"\n2",
        "sample_output": "4",
        "input_format": "Line 1: string s\nLine 2: integer k",
        "test_cases": [
            {"input": "\"ABAB\"\n2", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "\"AABABBA\"\n1", "expected_output": "4", "is_hidden": False, "weight": 1.0},
            {"input": "\"A\"\n0", "expected_output": "1", "is_hidden": True, "weight": 1.0},
            {"input": "\"ABBB\"\n2", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "\"BAAA\"\n0", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "\"AAAA\"\n2", "expected_output": "4", "is_hidden": True, "weight": 1.0},
            {"input": "\"ABCDE\"\n1", "expected_output": "2", "is_hidden": True, "weight": 1.0},
            {"input": "\"ABCDE\"\n2", "expected_output": "3", "is_hidden": True, "weight": 1.0},
            {"input": "\"KRSCDCSONAJNHLBMDQGIFCPEKPOHQI\"\n4", "expected_output": "6", "is_hidden": True, "weight": 1.0},
            {"input": "\"ABAA\"\n0", "expected_output": "2", "is_hidden": True, "weight": 1.0},
        ]
    }
]

